### ISSUE TITLE
Compilation not catching new changes

### ISSUE THREAD

**Issue by quasipickle** [sass/dart-sass#831] opened 2019-09-25 21:02 UTC
I've noticed with somewhat regularity that the compiled CSS does not include my latest changes.  It behaves like sass is compiling from a cache of sorts.  For example, if I add a background colour to an element, then compile - I get the background colour change.  Then I add a text colour and compile, and the text colour doesn't change.

I make lots of changes to my .scss files and I don't want to manually re-compile every time, so I'm running dart-sass with this command: `/usr/local/bin/dart-sass/sass -s compressed style.scss:style.css --watch`.  Actually I'm running a bash script wrapper that calls that command.

When I notice this behaviour, I `^C`  out, then run the command again.  I make a change in one of the watched files (add & remove a space), then compilation happens just fine.

This may be anecdotal, but I feel this happens more often when I make a lot of little changes rapidly.

I'm happy to debug or provide more info, but I'm not sure how or what will be helpful.

**Comment by nex3** [comment] 2019-09-26 11:03
This is a duplicate of #550. At this point, I've run out of debugging I can do myself without being able to reproduce the issue, so we need someone who can reliably reproduce the issue to dive into the Dart code and see what's going wrong there. See #550 for details.

**Closed by nex3** 2019-09-26 11:03 UTC

**Comment by quasipickle** [comment] 2019-09-26 15:21
Sorry about the duplication.
