### ISSUE TITLE
Cannot use scss file to generate css using dart-sass on the client side

### ISSUE THREAD

**Issue by Ratn** [sass/dart-sass#956] opened 2020-02-12 13:48 UTC
Hi,
I am trying to use sass on the client side to generate the css on the fly.
I'm able to use the string formatted data. for exmaple below snippet works well.
var scss_data = `
$font-stack:    Helvetica, sans-serif;
$primary-color: #333;

body {
  font: 100% $font-stack;
  color: $primary-color;
}
`;
var result = sass.renderSync({data: scss_data});

but when I put the content in a file(scss_content.scss) then it is not able to generate the css.
var result = sass.renderSync({file: scss_content.scss});
var result = sass.renderSync({file: "scss_content.scss"});
tried using the includePath but that didn't help.

I tried using the fibers but on the client side but fiber is not supported. Can someone provide help here. 
Thank you.

**Comment by nex3** [comment] 2020-02-12 20:54
Duplicate of #25

**Closed by nex3** 2020-02-12 20:54 UTC
