### ISSUE TITLE
@use allows to override variables without !default

### ISSUE THREAD

**Issue by eolant** [sass/dart-sass#1308] opened 2021-05-12 23:49 UTC
It's possible to override variables without `!default` that are provided in a third party library if it's in a separate variables file. 
Wondering if it's a bug or undocumented feature?

E.g. if you variables file defines a variable in `module/vars.scss`:
```sass
$color: red
```
We can redefine it like this in our own `variables.scss`:
```sass
@use 'module/vars' as *

$color: blue
```
And then in the main `style.scss`:
```sass
@use 'variables'
@use 'module/module'
```
Will result `module.scss`:
```sass
@use 'vars'

h1 {
  color: vars.$color
}
```
To actually be `blue`

See example here: https://stackblitz.com/edit/js-898q3x?file=variables.scss

**Comment by jathak** [comment] 2021-05-17 20:30
This is somewhat unintuitive, but it's intended behavior.

When a module is loaded with `@use`, you can reassign variables within that module. For example:

```scss
@use 'module/vars';

vars.$color: blue;
```

Your code with `@use as *` is equivalent to this, just for a module without a namespace.

**Closed by jathak** 2021-05-17 20:30 UTC
