### ISSUE TITLE
Conditional imports or Imports with sass variable names

### ISSUE THREAD

**Issue by SameerMakhija** [sass/dart-sass#456] opened 2018-08-17 17:51 UTC
We are trying to test 'dart-scss' to update our project form 'gulp-sass' to 'dart-sass'. We are able to run example provided at 

https://github.com/sass/sass-spec/pull/1278/files/75491a0689272b5f2127f83d09d6633f0aecf890

Is there any way we can conditionally imports sass files with dart-sass as we are trying to controls style through scss variables or apply multiple themes as mentioned below.

```
_themes.scss
    _A.scss
        $color: blue;

    _B.scss
        $color: green;

    _C.scss
        $color: yellow;

_variables.scss
   $theme: 'A';

_app.scss
    @import 'variables'

    .app {
        @if $theme == 'A' {
              @import 'themes/A';
        } @else if $theme == 'B' {
              @import 'themes/B';
        } @else if $theme == 'C' {
             @import 'themes/C';
        }

        color: $color;
    }


OR

app {
   @import 'themes/#{$theme}';
   color: $color;
}

```

**Comment by nex3** [comment] 2018-08-17 20:38
Duplicate of https://github.com/sass/sass/issues/739

**Closed by nex3** 2018-08-17 20:38 UTC
