### ISSUE TITLE
Add a CLI flag to control line endings (to allow CLRF on Windows)

### ISSUE THREAD

**Issue by HummingMind** [sass/dart-sass#1859] opened 2022-12-24 21:25 UTC
Hello,
When dart-sass compiles SCSS, the output CSS file ends up having the line endings as LF.

On windows, the default for line endings is CLRF. It's not an issue for source control with Git on Windows, because Git has a mode where it checks files in as LF and checks them out as CLRF.

You can keep the default mode as it is now, where it outputs LF, but please add a CLI flag for us Windows users to force the output CSS file(s) to have the line endings as CLRF. This would be optional and opt-in, so it wouldn't break anything for anyone.

Otherwise, various tooling such as IDEs, when used with Git on Windows, keep flagging the file as changed when nothing has actually changed other than the line endings format.

Thank you and happy holidays!
Max

**Comment by nex3** [comment] 2022-12-28 00:25
Duplicate of https://github.com/sass/sass/issues/2604

**Closed by nex3** 2022-12-28 00:25 UTC
