### ISSUE TITLE
1.33.0 breaking change with laravel-mix and bootstrap

### ISSUE THREAD

**Issue by greggunner** [sass/dart-sass#1319] opened 2021-05-21 14:31 UTC
I've had a laravel-mix project which I just updated to 1.33.0 of sass and on doing a laravel-mix build, I get an output that is filled with pages and pages of the new deprecation warning regarding the division symbol. I had to kill the process as it never ended and the output seemed to repeatedly output the same warning for the same line of code several times.

Downgrading to 1.32.13 resolved the issue and the project compiled.

software | version
-- | --
sass | 1.33.0 compiled with dart2js 2.13.0
node | 12.17.0
npm | 6.14.4
laravel-mix | 6.0.19
bootstrap | 4.6.0

**Comment by phil-w** [comment] 2021-05-21 14:37
Yeah it kills bootstrap 4 dead with that error. I would guess that my BS4 SASS files have slash in them.
As you say, never ending scrolling terminal garbage.

It's 1.33.0 wot breaks it, so presumably need to request whatever was working before that update.

**Comment by Awjin** [comment] 2021-05-21 18:09
Duplicate of https://github.com/sass/dart-sass/issues/672

**Comment by Awjin** [comment] 2021-05-21 18:46
https://github.com/sass/dart-sass/issues/672 is tracking the proper fix for this. For now, you can work around this by using the `--quiet` flag to silence the output (keep in mind that this will also mute non-deprecation `@warn`s).

**Comment by Awjin** [comment] 2021-05-21 20:54
That being said, we should not be emitting multiple deprecation warnings for the same source line of code. This is addressed by https://github.com/sass/dart-sass/pull/1322.

More broadly, we should probably add limits to the amount of warnings that can be printed. Filed a bug here: https://github.com/sass/dart-sass/issues/1323.

**Comment by stof** [comment] 2021-05-22 11:47
@Awjin @nex3 should this be closed now, or should it wait for the 1.33.1 release ?

**Closed** 2021-05-24 20:18 UTC
