### ISSUE TITLE
Add macos-arm64 build to the releases

### ISSUE THREAD

**Issue by cleydyr** [sass/dart-sass#1576] opened 2021-12-19 20:10 UTC
Currently there are 5 different combinations of operating system + processor architecture on the [Releases page](https://github.com/sass/dart-sass/releases). Can the release process include a macos-arm64 release to the Releases page?

Thank you!

**Comment by nex3** [comment] 2021-12-20 08:07
Duplicate of https://github.com/sass/dart-sass/issues/1125

**Closed by nex3** 2021-12-20 08:07 UTC

**Comment by cleydyr** [comment] 2021-12-20 08:43
Oops. My bad! Thank you triaging this. :D
