### ISSUE TITLE
Export 'Stylesheet-class' for easier lib-usage or provide String rendering function

### ISSUE THREAD

**Issue by MikeMitterer** [sass/dart-sass#127] opened 2017-02-28 16:23 UTC
I've just published https://github.com/MikeMitterer/dart-sass-var-transformer/blob/master/lib/sass_var_transformer.dart

This transformer reads the contents of a SCSS Files, replaces some vars and converts it to CSS.

I took your render function and slightly modified it.
My problem was that I had to search through your files to find the right imports.
This should be easier.

```dart
# I had to import these files
import 'package:sass/src/ast/sass.dart' as sass;
import 'package:sass/src/visitor/serialize.dart';
import 'package:sass/src/visitor/perform.dart';
import 'package:sass/src/io/vm.dart';
```

Converting not a file but the contents could be a nice feature for other libs too.

In my opinion there should bei either a global function for String rendering or it should be easier to get access to your Stylesheet-class.

However - Thanks for this package!

**Comment by nex3** [comment] 2018-04-14 01:18
Duplicate of #236

**Closed by nex3** 2018-04-14 01:18 UTC
Labels: Dart
