### ISSUE TITLE
sass importer api failed in latest version

### ISSUE THREAD

**Issue by shinken008** [sass/dart-sass#1764] opened 2022-07-28 07:20 UTC
## env
```sh
node@14.17.6
sass@1.50.0
```
## case 1  in sass@1.49.11
sass render option when `file` exists then the `importer` function did execute, node-sass success. I need to delete the `file` option to be successful. 

Awful, when I ran in sass@1.50.0 or the latest version, it did fail. 

Above issues, node-sass can be executed.
```js
// const sass = require('node-sass'); // success
const sass = require('sass');
const fs = require('fs')
const path = require('path')

const file = path.join(__dirname, './style/components/button.scss')
const data = fs.readFileSync(file, { encoding: 'utf-8' }).toString()

sass.render({
  // file, // run success in sass@1.49.11 when I delete. run fail in sass@1.50.0
  data,
  importer: (...args) => {
    const [url, prev] = args
    const prevFile = path.isAbsolute(prev) ? prev : file
    const _file = path.resolve(path.dirname(prevFile), url)

    console.log('_file >>>>>>>>>>', _file)    
    //  success flag log：_file >>>>>>>>>> /Users/xx/project/style-process-test/src/style/variables/default.scss
    //  success flag log：_file >>>>>>>>>> /Users/xx/project/style-process-test/src/style/mixins/index.scss
    
    return {
      file: _file,
      contents: fs.readFileSync(_file, { encoding: 'utf-8' }).toString() }
  }
}, function (error, result) {
  if (error) {
    console.error(error);
  }
  else {
    console.log(result.css.toString());
  }
});
```
```scss
// style/components/button.scss
@import '../variables/default.scss';
@import '../mixins/index.scss';
.button {
    // 
}
```
## case 2 nest importer in sass >= 1.37.5 failed

```scss
// style/components/button.scss
@import '../variables/default.scss';
@import '../mixins/index.scss';
.button {
    // 
}
```
nest import:
```scss
// @import '../mixins/index.scss';
@import './libs/absolute-center.scss';
@import './libs/clearfix.scss';
@import './libs/tint.scss';
```
when executing the success then console some log
```sh
_file >>>>>>>>>> /Users/xx/project/style-process-test/src/style/variables/default.scss
_file >>>>>>>>>> /Users/xx/project/style-process-test/src/style/mixins/index.scss
_file >>>>>>>>>> /Users/xx/project/style-process-test/src/style/mixins/libs/absolute-center.scss
_file >>>>>>>>>> /Users/xx/project/style-process-test/src/style/mixins/libs/clearfix.scss
_file >>>>>>>>>> /Users/x/project/style-process-test/src/style/mixins/libs/tint.scss
```
But failed in sass >= 1.38.0：
```sh
_file >>>>>>>>>> /Users/xx/project/style-process-test/src/style/variables/default.scss
_file >>>>>>>>>> /Users/xx/project/style-process-test/src/style/mixins/index.scss
```
nest import did not work in the `importer` API function.

**Comment by shinken008** [comment] 2022-07-28 07:37
Actually, sass >= v1.38.0, nest importer failed.

**Comment by shinken008** [comment] 2022-07-28 08:10
My repo is https://github.com/shinken008/style-process-test/blob/main/src/sass-importer.js

**Comment by nex3** [comment] 2022-08-02 20:34
It looks like your reproduction repository either doesn't exist or is marked as proivate.

**Comment by shinken008** [comment] 2022-08-03 09:09
> It looks like your reproduction repository either doesn't exist or is marked as private.

Oh, Sorry, I made a mistake aha. My reproduction repository is marked as public now.

**Comment by nex3** [comment] 2022-08-09 00:02
I'm not sure why this was working differently before, but the behavior in your reproduction case with the latest Sass version is correct. Relative loads from the filesystem _always_ take precedence over importer loads in order to preserve users' ability to locally reason about how their local files will work even if they have extra importers installed. Node Sass didn't always respect this, but that was a bug.

**Closed by nex3** 2022-08-09 00:02 UTC
Labels: bug, needs info
