### ISSUE TITLE
--watch folder stops working after error in imported files

### ISSUE THREAD

**Issue by mkrenner** [sass/dart-sass#751] opened 2019-07-03 09:45 UTC
sass .:. --watch

File main.scss:

    @import "./part1";

File _part1.scss:

    .myclass{
      width: 10px;
    }

1. make a syntax error in _part1.scss ->  error is reported to command line
2. fix the syntax error --> sass recompiles correctly
3. change anything in _part1.scss --> sass reports that it compiled, but it did nothing
4. make any syntax error in _part1.scss--> sass reports that it compiled successfully, but it did nothing

Environment:
Windows 10, sass --version --> 1.22.2 compiled with dart2js 2.4.0

**Comment by nex3** [comment] 2019-07-11 00:23
This is a duplicate of #550. At this point, I've run out of debugging I can do myself without being able to reproduce the issue, so we need someone who can reliably reproduce the issue to dive into the Dart code and see what's going wrong there. See #550 for details.

**Closed by nex3** 2019-07-11 00:23 UTC
