### ISSUE TITLE
A nested @media query can cause an outer query to be split unnecessarily

### ISSUE THREAD

**Issue by yukulele** [sass/dart-sass#1402] opened 2021-07-18 10:06 UTC
If `@media` is nested in another `@media`,  next `@media` are repeated.

Example:

input:
```scss
@media (min-width: 500px) {
    body{
        color: black;
        main{
            color:grey;
            @media (max-width: 1000px) {
                color: green;
            }
        }
        h1{
            color: red;
        }
        h2{
            color: blue;
        }
    }
}
```

output:
```css
@media (min-width: 500px) {
  body {
    color: black;
  }
  body main {
    color: grey;
  }
}
@media (min-width: 500px) and (max-width: 1000px) {
  body main {
    color: green;
  }
}
@media (min-width: 500px) {
  body h1 {
    color: red;
  }
}
@media (min-width: 500px) {
  body h2 {
    color: blue;
  }
}
```

expected:
```css
@media (min-width: 500px) {
  body {
    color: black;
  }
  body main {
    color: grey;
  }
}
@media (min-width: 500px) and (max-width: 1000px) {
  body main {
    color: green;
  }
}
@media (min-width: 500px) {
  body h1 {
    color: red;
  }
  body h2 {
    color: blue;
  }
}
```

**Comment by jathak** [comment] 2021-07-20 21:13
The actual and expected output here should be equivalent as far as semantics go. Combining the two rules into one media query _is_ probably more ideal, but making this cleaner is not something we're likely to have the bandwidth for.

If you really want to avoid these duplicate media queries, you could instead just move the nested query to the end of the outer one.

**Comment by nex3** [comment] 2022-06-15 23:58
Duplicate of #777.

**Closed by nex3** 2022-06-15 23:58 UTC
Labels: bug, cosmetic
