### ISSUE TITLE
At-rules may not be used within keyframe blocks

### ISSUE THREAD

**Issue by filipbekic01** [sass/dart-sass#2234] opened 2024-05-06 07:14 UTC
Worked well in version: 1.75.0
Bug in version: 1.76.0

I use Vue 3 (sass) in combination with tailwind. Code block that's causing error:

```
<style lang="scss" scoped>
@keyframes shake {
  10%,
  90% {
    @apply -translate-x-px;
  }

  20%,
  80% {
    @apply translate-x-0.5;
  }

  30%,
  50%,
  70% {
    @apply -translate-x-1;
  }

  40%,
  60% {
    @apply translate-x-1;
  }
}
</style>
```

<img width="1002" alt="image" src="https://github.com/sass/dart-sass/assets/16108768/9c3f4dff-828c-44ac-8487-438b7c7f1a82">

**Comment by nex3** [comment] 2024-05-06 20:46
Duplicate of https://github.com/sass/sass/issues/3859

**Closed by nex3** 2024-05-06 20:46 UTC
