### ISSUE TITLE
Cross-Media Query @extend

### ISSUE THREAD

**Issue by blackPeppper** [sass/dart-sass#1762] opened 2022-07-26 08:03 UTC
```sass
%font-size {
  font-size: 1.3rem
}

@media screen and (min-width: 700px) {
  .my-component {
    @extend %font-size
  }
}

// should be like this 
@media screen and (min-width: 700px) {
  .my-component {
    font-size: 1.3rem
  }
}

// but i get's this 

// You may not @extend selectors across media queries.
```

**Comment by nex3** [comment] 2022-08-02 20:40
Duplicate of sass/sass#1050

**Closed by nex3** 2022-08-02 20:40 UTC
