### ISSUE TITLE
Math Operators and SASS Variables do not work in CSS Custom Properties

### ISSUE THREAD

**Issue by allenretz** [sass/dart-sass#1090] opened 2020-09-18 04:47 UTC
The "+", "-", "*", and "/" Math Operations as well as SASS Variables don't compile correctly when used in CSS Custom Properties.

sass --version: "1.26.11 compiled with dart2js 2.9.3"

**Example: `Input.scss`**

```scss
$custom_variable_1: 50%;
$custom_variable_2: 58ch;


:root{

	// Testing Math Operations in CSS Custom Properties
	--custom-property-1: 20px * 2;                 // should be 40px
	
	// Testing SCSS Variables in CSS Custom Properties
	--custom-property-2: $custom_variable_1;       // should be 50%
	
	// Testing SCSS Variables with Math Operations in CSS Custom Properties
	--custom-property-3: $custom_variable_2 + 2ch; // should be 60ch
	
}
```

**`output.css`**

```scss
:root {
  --custom-property-1: 20px * 2;
  --custom-property-2: $custom_variable_1;
  --custom-property-3: $custom_variable_2 + 2ch;
}
```

**`expected_output.css`**

```scss
:root {
  --custom-property-1: 40px;
  --custom-property-2: 50%;
  --custom-property-3: 60ch;
}

```

**Comment by Awjin** [comment] 2020-09-18 14:51
Duplicate of https://github.com/sass/sass/issues/2898.

**Closed by Awjin** 2020-09-18 14:51 UTC
