### ISSUE TITLE
Prepare a way to disable warn about using named colors in interpolation

### ISSUE THREAD

**Issue by co3k** [sass/dart-sass#747] opened 2019-07-02 09:49 UTC
Our project gets a lot of warnings by dart-sass about named colors like the followings:

```
WARNING: You probably don't mean to use the color value blue in interpolation here.
It may end up represented as blue, which will likely produce invalid CSS.
Always quote color names when using them as strings or map keys (for example, "blue").
If you really want to use the color value here, use '"" + $color'.

    --#{$color}: #{$value};
        ^^^^^^
```

but the above solution doesn't make sense because the sass comes from bootstrap. https://github.com/twbs/bootstrap/blob/master/scss/_root.scss#L4

This type of warning is only false positive for us. We really want to disable this but we can't find any options to do so.

**Comment by nex3** [comment] 2019-07-02 19:14
Duplicate of https://github.com/sass/dart-sass/issues/672

To be clear though, this probably *is* caused by an error in your stylesheets. You're likely adding a value to Bootstrap's `$color` map whose key is a literal color object rather than a string, which may well produce invalid CSS in compressed mode.

**Closed by nex3** 2019-07-02 19:14 UTC
