### ISSUE TITLE
The fix for issue #806 leads to an infinity loop!

### ISSUE THREAD

**Issue by WolverinDEV** [sass/dart-sass#904] opened 2019-12-19 18:06 UTC
By adding the `.css` file ending to the "allow compile" list creates an infinity loop when the output file is within the source directory.

Steps to reproduce:
1. Create a file called `a.scss` with this content:
```
body { }
```
2. Execute the watch command: `sass --watch .`
3. Edit the file.

If you're lucky it will only compile the css file twice.
If you're not you might end up within an infinity loop.

**Comment by nex3** [comment] 2019-12-19 19:12
Duplicate of #853. I think you're using an outdated Sass version.

**Closed by nex3** 2019-12-19 19:12 UTC

**Comment by WolverinDEV** [comment] 2019-12-19 19:37
Updated to `1.23.7` issue persist.

**Comment by nex3** [comment] 2019-12-20 00:19
I can't reproduce this locally, and we have tests in place that verify that this exact problem doesn't reoccur. I suspect you're somehow still using an old Sass version.

**Comment by GenesisTMS** [comment] 2020-01-31 00:29
I can still reproduce this issue

- `npm install sass`
- create file `a.scss` and write to it

`sass --watch`
```
Compiled a.scss to a.css.
Compiled a.css to css.
```

`sass --version`
```
1.25.0 compiled with dart2js 2.7.0
```

Working on fedora

**Comment by nex3** [comment] 2020-02-24 20:28
@GenesisTMS I can't reproduce this.

**Comment by georgpukk** [comment] 2020-02-25 16:04
On Windows 10

`sass --version` [dart-sass-1.26.0-windows-x64.zip](https://github.com/sass/dart-sass/releases/tag/1.26.0)
```
1.26.0
```

`sass ./:./ --watch` _when saving creates an infinite loop_
```
Compiled main.scss to main.css.
Compiled main.css to main.css.
Compiled main.css to main.css.
Compiled main.css to main.css.
and so on...
```
`sass . --watch` _works fine_
```
Compiled main.scss to main.css.
```

**Comment by georgpukk** [comment] 2020-02-28 11:35
Updated to `1.26.1` and `sass . --watch` now too creates an infinite loop.

**Comment by WolverinDEV** [comment] 2020-02-28 11:39
Yeahr, good to see that I'm not the only one.
I suppose to may add a switch to ignore css files. This will quickly solve this.

**Comment by georgpukk** [comment] 2020-02-28 11:39
@nex3 This reproduces it on Windows 10
```
test("goes to infinite loop", () async {
      await d.file("test.scss", "a {b: c}").create();

      var sass = await watch(["."]);
      await expectLater(
          sass.stdout, emits('Compiled test.scss to test.css.'));
      await expectLater(sass.stdout, _watchingForChanges);
      await tickIfPoll();

      await d.file("test.scss", "r {o: g}").create();
      await expectLater(
          sass.stdout, emits('Compiled test.scss to test.css.'));

      await tickIfPoll();

      await d.file("test.scss", "x {y: z}").create();
      await expectLater(
          sass.stdout, emits('Compiled test.scss to test.css.'));

      await sass.kill();

      await d
          .file("test.css", equalsIgnoringWhitespace("x { y: z; }"))
          .validate();
    });
```

**Comment by georgpukk** [comment] 2020-02-28 12:43
> I suppose to may add a switch to ignore css files. This will quickly solve this.

@WolverinDEV The check to not compile .css file into itself seems to work the first time you hit save, but not for subsequent saves. Getting that fixed would be a better solution IMO.

**Comment by georgpukk** [comment] 2020-02-28 22:19
@nex3 This will fix it @ line 129 of  [`lib/src/executable/watch.dart`](https://github.com/sass/dart-sass/blob/master/lib/src/executable/watch.dart)
```
if (extension == '.css') {
        var stopThisMadness = false;
        var siblings = listDir(p.dirname(event.path));
        for (var sibling in siblings) {
          // if .css file has a .sass or .scss sibling of the same name
          if ((p.extension(sibling) == '.sass' || p.extension(sibling) == '.scss') && p.basenameWithoutExtension(event.path).compareTo(p.basenameWithoutExtension(sibling)) == 0 ) {
            stopThisMadness = true;
            break;
          }
        }
        if (stopThisMadness == true) {
          continue;
        }
      }
```
All the tests I ran it passed.
