### ISSUE TITLE
--watch not detect changes

### ISSUE THREAD

**Issue by Daijobou** [sass/dart-sass#1094] opened 2020-09-22 12:40 UTC
Version 1.26.11
```
scss/
├── base
│   └── controller.scss
└── app
    └── app.scss
```
Where app.scss is:

@import '../base/controller'

sass --watch scss/app tracks only app.scss file changes, but not in controller.scss

**Comment by Awjin** [comment] 2020-09-23 20:20
Duplicate of https://github.com/sass/dart-sass/issues/967.

You can work around this by watching both folders (`sass --watch scss/app scss/base`).

**Closed by Awjin** 2020-09-23 20:20 UTC

**Comment by raisen** [comment] 2021-01-16 10:06
I am not sure if this is related, but I am also having problems using the watch feature, and I have noticed it doesn't work when running under Virtualbox (Ubuntu guest) on a OSX host.
If I run the sass executable on the host, the watch feature works fine.
I'm using NFS shared folders on Virtualbox.

**Comment by nex3** [comment] 2021-01-19 21:49
Note that if you pass `--poll`, rather than trying to use a native filesystem watcher (which may or may not work on certain unusual circumstances like the one above) Sass will just manually check the filesystem for changes every so often. This is slower and more resource-intensive but should work everywhere.
