### ISSUE TITLE
-watch crashing on Arch

### ISSUE THREAD

**Issue by TheM3tabaron** [sass/dart-sass#740] opened 2019-06-27 18:46 UTC

**Comment by nex3** [comment] 2019-06-27 18:49
Please provide more information. What version of Sass are you using? How did you install it? How are you invoking Sass? What does your filesystem look like?  What stack trace does the crash produce?

**Comment by TheM3tabaron** [comment] 2019-06-27 18:59
_// Installed version:_
1 aur/dart-sass 1.20.1-1 (+4 0.11%) (Installed)
    Sass makes CSS fun again (canonical implementation)

_// delete css file, then stalls_
➜ sass --watch scss        
Compiled scss/fun.scss to scss/fun.css.
Sass is watching for changes. Press Ctrl-C to stop.

Deleted scss/fun.css.

Is this related to the packaging or to Dart-Sass?

Thanks for Sass

**Comment by nex3** [comment] 2019-06-27 19:02
So it's not crashing so much as just ceasing to receive filesystem notifications? This seems like a duplicate of https://github.com/sass/dart-sass/issues/550. At this point, we're stalled out on debugging I can do myself, and we need someone who can reliably reproduce the issue to dive into the Dart code and see what's going wrong there. See #550 for details.

**Comment by TheM3tabaron** [comment] 2019-06-27 19:03
his name is Not Sure:

➜ sass --version
Unexpected exception:
Invalid argument (uri): Value must be a String or a Uri: null


package:path/src/context.dart 1065:3    _parseUri
package:path/src/context.dart 986:44    Context.fromUri
package:path/path.dart 410:32           fromUri
package:sass/src/executable.dart 127:7  _loadVersion
package:sass/src/executable.dart 45:19  main

**Closed by nex3** 2019-06-27 19:02 UTC
Labels: bug, needs info

**Comment by TheM3tabaron** [comment] 2019-06-27 19:04
Just tested on my iMac. No issue with --watch there.

**Comment by TheM3tabaron** [comment] 2019-06-27 19:07
> So it's not crashing so much as just ceasing to receive filesystem notifications? This seems like a duplicate of #550. At this point, we're stalled out on debugging I can do myself, and we need someone who can reliably reproduce the issue to dive into the Dart code and see what's going wrong there. See #550 for details.

no. it just deletes the css file, and hangs.
Where can I find the error report?

**Comment by nex3** [comment] 2019-06-27 19:12
> ➜ sass --version
> Unexpected exception:
> Invalid argument (uri): Value must be a String or a Uri: null
> 
> package:path/src/context.dart 1065:3 _parseUri
> package:path/src/context.dart 986:44 Context.fromUri
> package:path/path.dart 410:32 fromUri
> package:sass/src/executable.dart 127:7 _loadVersion
> package:sass/src/executable.dart 45:19 main

You should probably file this as an issue against Arch's Sass package.

> Just tested on my iMac. No issue with --watch there.
> #550 are mac users

For my purposes, that issue covers watch failures on all operating systems.

**Comment by TheM3tabaron** [comment] 2019-06-27 19:34
found the shell script :)
All good.
Have a nice day.
