### ISSUE TITLE
20,000 lines of deprecation warnings - any way to disable these?

### ISSUE THREAD

**Issue by ffxsam** [sass/dart-sass#1324] opened 2021-05-21 21:36 UTC
Since updating `sass` in my Vue project, I now have 20,000 lines of deprecation warnings from Vuetify, a third-party library that I have no control over. Is there some way to silence deprecation warnings completely?

**Comment by Awjin** [comment] 2021-05-21 22:10
Duplicate of https://github.com/sass/dart-sass/issues/1319. We're actively working on a fix. Currently you can work around this by passing the `--quiet` flag to silence warnings.

**Closed by Awjin** 2021-05-21 22:10 UTC
