### ISSUE TITLE
@1.49.9 Skipped not serializable cache item 'Compilation/modules

### ISSUE THREAD

**Issue by HarshitSrivastava007** [sass/dart-sass#2060] opened 2023-08-10 14:10 UTC
Hi, currently getting below error with my production build compilation, Can someone suggest me to handle this?

Failed to compile.
       
       SassError: 2 arguments required, but only 1 was passed.
         ╷
       5 │     margin-bottom: rem(16px);
         │                    ^^^^^^^^^
         ╵
         node_modules/bootstrap/scss/mixins/_breakpoints.scss 75:7  media-breakpoint-down()

       SassError: expected "+", "-", "*", "/", ",", or ")".
          ╷
       78 │       padding: rem(6px 10px);
          │                        ^
          ╵
        
       SassError: 2 arguments required, but only 1 was passed.
           ╷
       113 │   font-size: rem(14px);
           │              ^^^^^^^^^
           ╵
       
       Import trace for requested module:

       SassError: expected "+", "-", "*", "/", ",", or ")".
          ╷
       73 │         padding: rem(8px 12px);
          │                          ^
          ╵
       
       Import trace for requested module:

       SassError: 2 arguments required, but only 1 was passed.
           ╷
       500 │       font-size: rem(15px);
           │                  ^^^^^^^^^
           ╵
       
       > Build failed because of webpack errors

**Comment by ntkme** [comment] 2023-08-10 16:04
Duplicate of #2059. See https://github.com/sass/dart-sass/issues/2059#issuecomment-1673498459

**Comment by connorskees** [comment] 2023-08-14 00:06
Perhaps this change should be pushed back to a later release, and a deprecation warning be emitted instead? Disallowing function names like `pow`, `rem`, and `sin` seems quite disruptive, even if in the pursuit of CSS compatibility.

Otherwise, it would likely be helpful to add a warning if a user tries to either create a function with one of the newly reserved names or if a user tries to call one of these newly reserved functions while a user-defined function of the same name is in scope.

**Comment by amxmln** [comment] 2023-08-14 09:31
I just ran into this as well and it took me as a surprise as I would consider this a breaking change.

Why are these new functions not functions like `linear-gradient` which can be overridden? 🤔

**Comment by connorskees** [comment] 2023-08-14 13:34
> Why are these new functions not functions like linear-gradient which can be overridden

Sass performs simplification of these sorts of functions, so they're type-checked to what the browser expects and have special behavior when possible. See an example of this [here](https://connorskees.github.io/grassmeister/?v=YSB7CiAgICBjb2xvcjogY2FsYygxICsgMSk7Cn0=) (note this repl doesn't yet support these new functions).

**Comment by Goodwine** [comment] 2023-08-15 21:43
> Perhaps this change should be pushed back to a later release, and a deprecation warning be emitted instead? Disallowing function names like pow, rem, and sin seems quite disruptive, even if in the pursuit of CSS compatibility.

I agree, this potential issue wasn't caught during the proposal nor implementation. It's a lesson to be learned for an issue that I think will reappear for the [Color Level 4, New Color Spaces](https://github.com/sass/sass/blob/main/proposal/color-4-new-spaces.md#color) proposal. (for example, the new [`color()`](https://github.com/sass/sass/blob/main/proposal/color-4-new-spaces.md#color) function).

Natalie is currently out, we're waiting for her return before any further releases :)

Personally (and this is not authoritative) I agree it should have been pushed back with a deprecation warning period, or rolledback into 1.65.2 immediately. Now I feel it is "too late" and reverting would break those who made changes in response to this version which has been out for almost a week, so reverting is more difficult. I imagine something in between like "if there is a calc function available as a function without a namespace, don't parse as calculation and evaluate as function and print a warning". Not sure if that's the path we'll take.

> I just ran into this as well and it took me as a surprise as I would consider this a breaking change.

https://sass-lang.com/documentation/breaking-changes/calc-functions/

> why are these new functions not functions like linear-gradient which can be overridden?

Functions like `linear-gradient` are not processed nor validated by Sass. They are "unknown" to Sass, and these "unknown" functions are emitted as-is (the arguments are still evaluated and resolved tho). You can even implement your own `@function linear-gradient()` to do something completely different.

Before the breaking change, functions like `rem()` or `pow()` were also not being parsed any differently, we just had global functions available for them. But now, all of these functions are being parsed as calculations with new validations and everything. This was already the case for `min()` and `max()`.

**Comment by Goodwine** [comment] 2023-08-15 21:50
FWIW, looking for something else for an unrelated issue, I stumbled upon this relevant bug report for the same problem with min/max 🤔 

https://github.com/sass/sass/issues/3142

**Comment by amxmln** [comment] 2023-08-16 08:09
>> I just ran into this as well and it took me as a surprise as I would consider this a breaking change.

> https://sass-lang.com/documentation/breaking-changes/calc-functions/

For some reason I thought `dart-sass` was following SemVer, so I hadn’t checked, my bad.

Thanks for all the explanations, I can understand what happened. Renaming the function and retraining some muscle memory is probably the simplest solution, although I do feel like a bunch of people were caught quite off-guard by this.

**Comment by nex3** [comment] 2023-08-17 18:07
I've reopened https://github.com/sass/sass/issues/3504 to track this.

**Closed by nex3** 2023-08-17 18:07 UTC
