### ISSUE TITLE
@use above comments

### ISSUE THREAD

**Issue by cpof-tea** [sass/dart-sass#1033] opened 2020-06-21 22:13 UTC
Turns out, sass compiles `@use` even above comments.
Here's example (L - input, R - output):

![image](https://user-images.githubusercontent.com/29537473/85236211-a3e90080-b424-11ea-9339-f9164c9e8ab0.png)

Don't know, it's a bug or feature. Any suggestions?
I have to back to `@import` instead of `@use`, for now.

sass 1.26.8

**Comment by Awjin** [comment] 2020-06-23 17:44
Duplicate of https://github.com/sass/sass/issues/2848. A workaround would be to apply purgecss to the generated css instead.

**Closed by Awjin** 2020-06-23 17:44 UTC

**Comment by cpof-tea** [comment] 2020-07-02 19:12
@Awjin and what workaround would you suggest in next case with 3rd party modules?
```sass
/*!
 * Some copyright before
 */
@forward "root";
@forward "reboot";
@forward "type";
@forward "images";
@forward "code";
@forward "grid";
// purgecss start ignore
@forward "tables";
@forward "forms";
@forward "buttons";
// purgecss end ignore
@forward "transitions";
@forward "dropdown";
@forward "button-group";
@forward "input-group";
@forward "custom-forms";
@forward "nav";
@forward "navbar";
@forward "card";
@forward "breadcrumb";
@forward "pagination";
@forward "badge";
```

**Comment by Awjin** [comment] 2020-07-06 20:38
I don't understand how this demonstrates a different use case. If purgecss is applied only to the generated css, it shouldn't need to know about the source of the Sass.

**Comment by cpof-tea** [comment] 2020-07-07 21:33
Sorry, I put the wrong comments (`// ...` instead of `/* ... */`) in the post. Edited

For example, you configured a library by `@forward`s or `@use`s and include every module you're using.
From most modules some selectors used by app, so the rest aren't needed.
From some of modules (tables, forms, buttons) every selector are used by your app or will be used by app scripts. Some of the selectors aren't present in the html source, but you need to keep them all by wrapping them with purgecss ignore section comments, which should have be in right place in the generated css.

But Sass just throws your comments at the end in the generated css (including copyright comment, which should have been at the beginning, by the way)

**Comment by Awjin** [comment] 2020-07-09 20:16
If you need to preserve the order of comments, I would recommend using [`meta.load-css()`](https://sass-lang.com/documentation/modules/meta#load-css) instead of `@forward` to load these modules.

**Comment by cpof-tea** [comment] 2020-07-09 20:25
This not obvious behaviour of `@use` and `@forward` with comments should be highlighted in the Sass docs, I think.

**Comment by nex3** [comment] 2020-07-09 21:25
User-facing documentation needs to balance detail with readability in order not to become totally overwhelming for people casually skimming it. It can't ever explain every possible corner case or piece of behavior, or it would just read like a formal specification. In fact, we already have [a formal specification](https://github.com/sass/sass), which *does* describe this behavior.

**Comment by edwinbradford** [comment] 2021-01-10 11:28
WordPress stipulates the [theme description](https://developer.wordpress.org/themes/basics/main-stylesheet-style-css/) should come at the head of the css. After migrating to dart sass and changing all the @import rules to @use rules in the main style sheet my theme's description is now at the end of the compiled css.

The good news is it doesn't seem to break anything but I thought you should know this will affect all WordPress theme developers.

**Comment by EmSixTeen** [comment] 2023-02-01 14:48
> In fact, we already have [a formal specification](https://github.com/sass/sass), which _does_ describe this behavior.

_Where?_

**Comment by nex3** [comment] 2023-02-01 23:49
If you're looking for the section that explains how the final CSS is stitched together, [it's here](https://github.com/sass/sass/blob/main/spec/at-rules/extend.md#resolving-a-modules-extensions).

**Comment by yCodeTech** [comment] 2023-04-10 03:03
> If you're looking for the section that explains how the final CSS is stitched together, [it's here](https://github.com/sass/sass/blob/main/spec/at-rules/extend.md#resolving-a-modules-extensions).

That link ALSO doesn't describe the behaviour of comments being out of whack! It is also just a bunch of mumbo jumbo that only the devs know how to interpret as normal day-to-day English.

The comments being moved should NOT be the intended behaviour.
