### ISSUE TITLE
installation via brew broken for the latest release

### ISSUE THREAD

**Issue by mraleph** [sass/dart-sass#942] opened 2020-01-25 12:50 UTC
```
$ brew install sass/sass/sass
==> Installing sass from sass/sass
==> Downloading https://github.com/sass/dart-sass.git/archive/1.25.1-test.1.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "sass"
Download failed: https://github.com/sass/dart-sass.git/archive/1.25.1-test.1.tar.gz
```

I think there is a typo in the URL - it should be without `.git` after `dart-sass`.

**Comment by nex3** [comment] 2020-01-26 06:56
Duplicate of https://github.com/sass/homebrew-sass/issues/28

**Closed by nex3** 2020-01-26 06:56 UTC
