### ISSUE TITLE
Output differ when using `@use` rule instead of `@import`

### ISSUE THREAD

**Issue by xavierfoucrier** [sass/dart-sass#1282] opened 2021-04-12 12:13 UTC
I am currently migrating one of my project to use the new sass `@use` rule, as suggested [in the official documentation](https://sass-lang.com/documentation/at-rules/use), and remove the old `@import` one. This project uses `PurgeCSS` to remove unused classes from the output, really useful to reduce bundle size.

The fact is that, when using `@use`, the output differs.

For example, this code:
```scss
/*! purgecss start ignore */
@import 'component/a';
.b { color: grey; }
/*! purgecss end ignore */
```

Was previously producing:
```css
/*! purgecss start ignore */
.a { color: red; }
.b { color: grey; } 
/*! purgecss end ignore */
```

But now, if I switch to `@use` rule, the same code give a different build result:
```scss
/*! purgecss start ignore */
@use 'component/a';
.b { color: grey; }
/*! purgecss end ignore */
```

```css
.a { color: red; }
/*! purgecss start ignore */
.b { color: grey; }
/*! purgecss end ignore */
```

Making the component `a` to be purged, as comments moved... when he shouldn't.

I fully understand than using `@use` will make the sass works as "modules", but what I don't understand is why the comments that are placed in a specific order are not preserved in the compilation process.

Thanks a lot for further explanation :wink: 

Here are some additional informations about my setup:
- Operating System: Windows 7 x64
- Node Version: 13.14.0
- NPM Version: 6.14.9
- webpack Version: 5.30.0
- sass-loader Version: 11.0.1

> I have previously posted this on the `sass-loader` repository as I work with webpack, but look related to sass (dart) instead.

**Comment by Awjin** [comment] 2021-04-13 20:26
Duplicate of https://github.com/sass/dart-sass/issues/1033

**Closed by Awjin** 2021-04-13 20:26 UTC

**Comment by xavierfoucrier** [comment] 2021-04-13 22:26
Hi @Awjin,

Thanks for highlighting that this is a duplicate... but looks like there is no workaround or something that fix this bug? :thinking:

**Comment by Awjin** [comment] 2021-04-14 22:02
I wouldn't call it a bug, since this is intended behavior of the module system.

As described in https://github.com/sass/dart-sass/issues/1033, workarounds include writing `purgecss` comments in the emitted CSS instead of the Sass code, or by using `meta.load-css()` instead of `@use`.

**Comment by xavierfoucrier** [comment] 2021-04-15 08:41
Hi @Awjin,

Sorry to bother you again.

The fact is that I don't want to purge all CSS code, only some parts, that's why I am using an entry point in my setup, called `build.scss`, and then put my `purgecss` comments before/after to only englobe the code that I want to be purged.

So from my point of view it's only impossible to put only `purgecss` comments in the emitted CSS, the comments need to be put like this:

```scss
// build.scss

@use 'vendor/library'; // big css framework that need to be purged
@use 'vendor/another'; // another vendor asset

/*! purgecss start ignore */

@use 'vendor/something-important';
@use 'component/my-component';
@use 'component/another-one';

/*! purgecss end ignore */

```

I guess I am not the only one in that case.

**Comment by ivodolenc** [comment] 2021-04-21 19:19
Hi @Awjin @xavierfoucrier, I also came across because of `purgecss` comments.

This is also important for `copyright` info (at the beginning of the file), especially for `library` authors.

Example of the `main.scss` file on `npm`:

```scss
/*! nevo framework | MIT License */

@forward 'settings';
@forward 'base';
@forward 'utilities';
```

Current output: 

```scss
// styles

/*! nevo framework | MIT License */
```

Expected output: 

```scss
/*! nevo framework | MIT License */

// styles
```

Can you please give some hint, do you plan to bring back the old behavior (for comments)? Obviously, the current workaround mentioned above doesn't solve this issue.

**Comment by xavierfoucrier** [comment] 2021-04-21 21:46
@ivodolenc I totally agree, the mentioned workaround doesn't solve the issue..

@nex3 can you have a look at this please and give a feedback?

Thanks a lot!

**Comment by ivodolenc** [comment] 2021-04-22 13:12
The above workaround doesn't solve this, because if we want to use a framework from npm for example, then we don't have access to certain pieces of code or files and cannot add comments as suggested in the workaround.

Example:

```scss
/*! purgecss start ignore */

@use 'nevo' as *;

/*! purgecss end ignore */
```

Current output:

```scss
// styles

/*! purgecss start ignore */
/*! purgecss end ignore */
```

Expected output:

```scss
/*! purgecss start ignore */

// styles

/*! purgecss end ignore */
```

**Comment by xavierfoucrier** [comment] 2021-05-01 21:20
@Awjin @nex3 sorry to bother you again, but this is a serious issue with no workaround at this time. Thanks for reply. 👍

**Comment by xavierfoucrier** [comment] 2021-05-06 15:28
@ivodolenc here are some workarounds, for the moment:

1. **keep `@import` rules** on your main entry point, same as before

```scss
@import 'component/vendor';

/*! purgecss start ignore */
@import 'component/a';
@import 'component/b';
/*! purgecss end ignore */
```

> You can still continue to use `@use` rule inside `component/a` and `component/b`.

2. create **two files with start/end PurgeCSS comments**, then englobe the portion you want to ignore from PurgeCSS

```scss
@use 'component/vendor';

@use 'util/purgecss-start'; // <-- contains /*! purgecss start ignore */
@use 'component/a';
@use 'component/b';
@use 'util/purgecss-end'; // <-- contains /*! purgecss end ignore */
```

Not really funny right now.

**Comment by ivodolenc** [comment] 2021-05-07 10:50
@xavierfoucrier nice tips, thanks for sharing that 👌 But yeah, I definitely agree that this topic is something worth discussion.

Unfortunately, according to comments on this topic by the team, I don’t think they intend to deal with it. As far as I understand, it would be difficult to implement this functionality (isolate comments) into existing code.

**Comment by xavierfoucrier** [comment] 2021-05-07 11:12
@ivodolenc I finally ended to make my code works with 2 additional files with start/end PurgeCSS comments inside. As the `@import` keyword will be deprecated [in a near future](https://sass-lang.com/documentation/at-rules/import), it's better to continue with `@use` instead.

Happy coding! :tada: 

> @Awjin thanks again for the fast answer on this topic. I know that it's important to focus on important issues on a large project like SASS, but closing some without giving a "valid" workaround is non-benefit for the whole developer community. I manage open source projets too, so I understand the consideration project manager made when closing issues. I hope `@use` rule will continue to evolve to cover as most features of the `@import` rule as possible.

**Comment by call0fcode** [comment] 2022-04-27 21:46
> @ivodolenc I finally ended to make my code works with 2 additional files with start/end PurgeCSS comments inside. As the `@import` keyword will be deprecated [in a near future](https://sass-lang.com/documentation/at-rules/import), it's better to continue with `@use` instead.
> 
> Happy coding! tada

I've used the same strategy to retain WordPress theme comments on the top of my result .css file as they are absolutely necessary for the themes to work properly. I also consider a good practice using `@use` instead of `@import `these days 😉.
