### ISSUE TITLE
Reusing a module without `with`

### ISSUE THREAD

**Issue by fhred** [sass/dart-sass#857] opened 2019-10-19 14:35 UTC
I get a compilation error that I can't explain myself. Here is a minimal example:

main.scss:
```css
@use "modules/_popup" with (
    // some code
);

@use "pages/_challenges" with (
    // some code
);
```

pages/_challenges:
```css
@use "../modules/_popup";
```

`sass main.scss` fails with:
```
Error: This module was already loaded, so it can't be configured using "with".
  ╷
8 │ @use "../modules/_popup";
  │ ^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  pages/_challenges.scss 8:1  @use
  main.scss 77:1              root stylesheet
```

I use the `sass` package from npm, version: 1.23.0 compiled with dart2js 2.5.1

Might be related to #854.

**Comment by nex3** [comment] 2019-10-22 00:34
Yeah, this is a duplicate of #854.

**Closed by nex3** 2019-10-22 00:34 UTC
