### ISSUE TITLE
Support for specifying a config file for use with `sass` on the command line

### ISSUE THREAD

**Issue by mimidotsuser** [sass/dart-sass#1056] opened 2020-08-13 12:55 UTC
Is there a plan to add support for configuration file to hold compilation options while using the command line? This would be a great feature if someone was able to specify the config file using a flag name e.g. `sass ---config  sassconfig.json`

**Comment by Awjin** [comment] 2020-08-13 21:12
Duplicate of https://github.com/sass/sass/issues/2669.

**Closed by Awjin** 2020-08-13 21:12 UTC
