### ISSUE TITLE
[1.40] 0.25rem and 0 are incompatible

### ISSUE THREAD

**Issue by caugner** [sass/dart-sass#1476] opened 2021-09-14 08:12 UTC
Dependabot opened a merge request to bump sass from 1.39.0 to 1.40.0 and this caused the following build error:

```
ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: 0.25rem and 0 are incompatible.
  ╷
9 │       $return: append($return, max($value, 0));
  │                                    ^^^^^^ 0.25rem
  │                                            ━ 0
  ╵
  node_modules/bootstrap/scss/mixins/_border-radius.scss 9:36   valid-radius()
  node_modules/bootstrap/scss/mixins/_border-radius.scss 19:20  border-radius()
  node_modules/bootstrap/scss/_images.scss 18:3                 @import
  node_modules/bootstrap/scss/bootstrap.scss 14:9               @import
  resources/sass/app.scss 8:9                                   root stylesheet
    at /builds/***/***/node_modules/webpack/lib/NormalModule.js:316:20
    at /builds/***/***/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /builds/***/***/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/builds/***/***/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /builds/***/***/node_modules/sass-loader/dist/index.js:62:7
    at Function.call$2 (/builds/***/***/node_modules/sass/sass.dart.js:95525:16)
    at _render_closure1.call$2 (/builds/***/***/node_modules/sass/sass.dart.js:83704:12)
    at _RootZone.runBinary$3$3 (/builds/***/***/node_modules/sass/sass.dart.js:28038:18)
    at _FutureListener.handleError$1 (/builds/***/***/node_modules/sass/sass.dart.js:26568:21)
    at _Future__propagateToListeners_handleError.call$0 (/builds/***/***/node_modules/sass/sass.dart.js:26867:49)
    at Object._Future__propagateToListeners (/builds/***/***/node_modules/sass/sass.dart.js:12499:77)
    at _Future._completeError$2 (/builds/***/***/node_modules/sass/sass.dart.js:26713:9)
    at _AsyncAwaitCompleter.completeError$2 (/builds/***/***/node_modules/sass/sass.dart.js:26382:12)
    at Object._asyncRethrow (/builds/***/***/node_modules/sass/sass.dart.js:12302:17)
    at /builds/***/***/node_modules/sass/sass.dart.js:1822:20
    at _wrapJsFunctionForAsync_closure.$protected (/builds/***/***/node_modules/sass/sass.dart.js:12327:15)
 @ ./resources/sass/app.scss
ERROR in ./resources/sass/app.scss (./node_modules/css-loader??ref--7-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--7-4!./node_modules/sass-loader/dist/cjs.js??ref--7-5!./resources/sass/app.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: 0.25rem and 0 are incompatible.
  ╷
9 │       $return: append($return, max($value, 0));
  │                                    ^^^^^^ 0.25rem
  │                                            ━ 0
  ╵
  node_modules/bootstrap/scss/mixins/_border-radius.scss 9:36   valid-radius()
  node_modules/bootstrap/scss/mixins/_border-radius.scss 19:20  border-radius()
  node_modules/bootstrap/scss/_images.scss 18:3                 @import
  node_modules/bootstrap/scss/bootstrap.scss 14:9               @import
  resources/sass/app.scss 8:9                                   root stylesheet
 @ ./resources/sass/app.scss 2:14-253
```

My assumption would be that the unit doesn't matter for zero values.

See also: https://github.com/twbs/bootstrap/issues/34969

**Comment by nex3** [comment] 2021-09-14 08:16
Duplicate of https://github.com/sass/sass/issues/3142

**Closed by nex3** 2021-09-14 08:16 UTC
