### ISSUE TITLE
Can't `@use` the package.json imports, the default namespace "" is not a valid Sass identifier.

### ISSUE THREAD

**Issue by MuhammadSawalhy** [sass/dart-sass#1635] opened 2022-02-18 07:49 UTC
I am trying to use the new ["imports" field in package.json](https://nodejs.org/api/packages.html#imports), (release since node v13.1.0, v12.16.0). So I added these lines in package.json

```json
  "imports": {
    "#style/*": "./src/style/*"
  }
```

I also have this file "src/style/_theme.scss". The `.scss` files are compiled using `webpack@5.52.0`, `sass-loader`, and `sass@(1.43.2 compiled with dart2js 2.14.3)`. But here is what the logs of webpack says:

```
ERROR in ./src/pages/Partners/Statistics.module.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!./node_modules/sass-loader/dist/cjs.js!./src/pages/Partners/Statistics.module.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: The default namespace "" is not a valid Sass identifier.

Recommendation: add an "as" clause to define an explicit namespace.
  ╷
1 │ @use "#style/_theme";
  │ ^^^^^^^^^^^^^^^^^^^^
  ╵
  src/pages/Partners/Statistics.module.scss 1:1  root stylesheet
 @ ./src/pages/Partners/Statistics.module.scss 8:6-192 22:17-24 26:7-21 58:25-39 59:36-47 59:50-64 63:6-73:7 64:54-65 64:68-82 70:42-53 70:56-70 72:21-28 83:0-162 83:0-162 84:22-29 84:33-47 84:50-64 61:4-74:5
 @ ./src/pages/Partners/Statistics.js 13:0-47 26:30-56 58:15-42
 @ ./src/components/Navigation/getLinks.js 43:21-62
 @ ./src/index.js 19:0-56 47:30-38

27
```

Note that I tried `@use "#style/theme";` but the same error occurred.

I also used the [self-referencing](https://nodejs.org/api/packages.html#self-referencing-a-package-using-its-name) with "exports" field before trying to use "imports" and it worked.

```scss
@use "package-name/style/theme";
```

```json
  "name": "package-name",
  "exports": {
    "./style/*": "./src/style/*",
  }
```

**Comment by Awjin** [comment] 2022-02-18 21:33
Since Sass treats imports as URLs, the `#` in `@use "#style/theme"` causes Sass to interpret it as a URL fragment, making Sass think the default namespace is "".

There are potentially two ways to fix this:
1. URL-escape the `#` (this may or may not work, depending on how `sass-loader` is resolving this import)
2. Do what the error message suggests, and import it with a namespace, e.g. `@use "#style/theme" as namespace`

**Closed by Awjin** 2022-02-18 21:33 UTC

**Comment by MuhammadSawalhy** [comment] 2022-03-18 11:36
> So I would recommend using a different prefix than # for the prefix

The [official documentations](https://nodejs.org/api/packages.html#imports) says

> Entries in the imports field must be strings starting with #.

---------

> the webpack sass-loader currently uses the legacy JS API, which does not rely fully on URLs

After some issue I opened related to the imports field, I finally thought that the solution is in the hands of sass-loader. But I gave up making issues about the standard imports field that doesn't have a good attention from the open-source community.

**Comment by fluidsonic** [comment] 2024-06-07 21:18
I also ran into this issue today and spent hours debugging.

`package.json`-based import aliases using `"imports"` are becoming more common, and likely the norm at some point.

[By design](https://nodejs.org/api/packages.html#subpath-imports), such import aliases must start with a `#` sign. Webpack is perfectly capable of resolving these aliases, even in SASS files. With Turbo, Next.js is moving towards [recommending](https://turbo.build/repo/docs/guides/tools/typescript#use-nodejs-subpath-imports-instead-of-typescript-compiler-paths) `package.json`-based `"imports"` and some features will [require it](https://turbo.build/repo/docs/core-concepts/internal-packages#limitations-and-tradeoffs), such as Just-in-Time package compilation. TypeScript and IDEs keep expanding their support.

Looking at the suggestions / potential workarounds in this GitHub issue so far:

- URL-escaping the import seems highly inconvenient (and it doesn't work either). It's supposed to be `#…` consistently and should work in exactly the same way as it does in JavaScript, TypeScript, and other files - no need for escaping and weird UX. Manually escaping the `#` in a `@use` directive doesn't work anyway because the escaped version will be handed over to `sass-loader` and then `webpack` for resolution, which will fail. Webpack expects paths, not URLs.
- When developers migrate from `@use "@/style/theme"` to `@use "#style/theme"`, this issue here will come up. Using an explicit namespace with `@use "#style/theme" as theme` is possible but redundant and will likely have to be done in **all** SASS files and for multiple imports per file. It should work exactly the same way as before.

### Suggestion
IMHO the solution here is simple. It's very unlikely that anyone wants to import anything from a URL that only has a fragment component and nothing else. It doesn't point to any loadable resource (just to the importing SASS file itself) and it only makes sense for advanced import resolution.

**If all components of the URL except the fragment are empty**, the namespace is derived in the following way:
1. Use the fragment without the leading `#` sign.
2. Treat the fragment as the path and split it into segments.
3. Use the last path segment to derive the `basename`
4. Proceed as usual.

The adjustment would be required here:

https://github.com/sass/dart-sass/blob/5ddd7fc723d5be220a38882010469bbd7390a3e7/lib/src/parse/stylesheet.dart#L1444-L1447

I quickly tested that solution in my private project by modifying the JS-transpiled `sass` library directly in that way and it works like a charm.

**Comment by nex3** [comment] 2024-06-07 23:56
Sass loads are not JavaScript imports, and expecting them to use the same syntax and work the same way is never going to work out. Specifically, Sass loads are URLs and ES6 module specifiers are not, which is going to cause differences. The best way to handle this is for importers to avoid using `#` as a meaningful character in Sass modules; I've filed https://github.com/webpack-contrib/sass-loader/issues/1205 to encourage WebPack's Sass importer to do this.

**Comment by Carnageous** [comment] 2025-02-28 11:06
I'm sorry to re-open this, and I fully understand that Sass should not handle imports with a `#` prefix like Nodejs defines them.
However, I am wondering if the 'workaround' with manually namespacing (like `@use "#style/index" as index`) actually works?

I tried this for a very long time with different configurations, but both dart-sass and sass-embedded run into module import loops and report that the `index` module is already being loaded, even if there is just a single `.scss` file. See [this stackblitz reproduction](https://stackblitz.com/edit/vitejs-vite-suxihvhf?file=src%2FApp.scss) for example.

It uses `dart-sass`, `vite` and the `modern-compiler` option

**Comment by stof** [comment] 2025-02-28 11:44
Sass imports are using a URI, not a node.js import specifier. In a URL, `#style/index` defines a fragment in the URL. It is not part of the path.
An explicit index might solve the error reported for the default namespace. But it will likely not import the expected thing as the Sass FilesystemImporter ignores the fragment entirely in the URL.

**Comment by Carnageous** [comment] 2025-03-03 14:02
@stof I opened an [issue with vite](https://github.com/vitejs/vite/issues/19560#issuecomment-2694444279), and they claim it's something with the scss modern API. However, We will just be switching to `$` imports for SCSS files for now. Thanks for your help
