### ISSUE TITLE
--watch fails to recompile changes to file once an error has occurred

### ISSUE THREAD

**Issue by Chris-Poirier** [sass/dart-sass#902] opened 2019-12-18 23:09 UTC
I am running dart-sass with the following command line:
sass.bat --watch source\:output\ --style=compressed --no-source-map --no-charset --no-error-css --no-stop-on-error --no-color --unicode --no-quiet --no-trace

If I get an error in a partial scss file, such as a stray } , the css file fails to compile (which is expected), and when I fix the error it compiles properly. The issues is that if I then make a change to the partial scss file, the change is not reflected in the compiled css. In order to work-around this, I need to remove the @import, save, re-add the @import, and re-save the partial file.

I tested with using @use instead of @import, and the issue still persists.

**Comment by nex3** [comment] 2019-12-18 23:49
This is a duplicate of #550. At this point, I've run out of debugging I can do myself without being able to reproduce the issue, so we need someone who can reliably reproduce the issue to dive into the Dart code and see what's going wrong there. See #550 for details.

**Closed by nex3** 2019-12-18 23:49 UTC
