### ISSUE TITLE
RGB colors instead HEX after compilation

### ISSUE THREAD

**Issue by Spaceknyte** [sass/dart-sass#2466] opened 2024-12-13 08:24 UTC
I noticed that starting with version 1.79.0, all colors are converted to RGB. 

SCSS:
`background-color: color.mix($color-black, $color-primary, 5%);`

CSS:
`background-color: rgb(10.45, 146.3, 113.05);`

In version 1.78.0 I get what I want:
`background-color: #0a9271;`

How to configure this in new versions?

**Comment by nex3** [comment] 2024-12-14 00:56
Duplicate of https://github.com/sass/dart-sass/issues/2456

**Closed by nex3** 2024-12-14 00:56 UTC
