### ISSUE TITLE
--watch ignores @import/@use file changes outside of input directory

### ISSUE THREAD

**Issue by Mardak** [sass/dart-sass#1359] opened 2021-06-15 06:52 UTC
Watching changes with `sass styles/in.scss:out.css --watch` with `1.34.1 compiled with dart2js 2.13.1`
```scss
styles/in.scss:
@import "../components/Foo";

components/_Foo.scss:
/* foo */
```
Correctly compiles initially to:
```css
out.css:
/* foo */
```
But then modifying `components/_Foo.scss` which is not contained within the input's directory:
```diff
-/* foo */
+/* bar */
```
does not trigger a recompilation of `out.css` until restarting the `sass` command which then correctly results in:
```css
out.css:
/* bar */
```

**Comment by jathak** [comment] 2021-06-16 20:20
Duplicate of #967. Unfortunately, this isn't really feasible for us to support

**Closed by jathak** 2021-06-16 20:20 UTC

**Comment by Mardak** [comment] 2021-06-16 20:56
Ah thanks. That other issue was linked from https://github.com/sciety/sciety/commit/8adf74a6e958e93a5442d1fba3674afcbe12eb58 which seems to be sufficient workaround.

**Comment by PierBover** [comment] 2021-07-04 19:51
@jathak isn't there a workaround? Maybe you could add an option to the CLI to manually add additional watched folders?

The JS version of `dart-sass` which can be used with Webpack is extremely slow.

Without this feature many will have no option than to resort to the deprecated `node-sass`.
