### ISSUE TITLE
support quietDeps flag

### ISSUE THREAD

**Issue by giano** [sass/dart-sass#1333] opened 2021-05-25 09:46 UTC
As most of the developers can't actually fix deprecated code inside external libraries (aside from updating them) it would be nice to respect newly added **quietDeps** flag in library options to silence deprecation warnings from external libraries. 

Would be great to emit a less clogged output from webpack's sass-loader, for example.

```
{
    loader: 'sass-loader',
    options: {
        implementation: require('sass'),
        sassOptions: {
            quietDeps: true
        },
    },
}
```

Thank you

**Comment by nex3** [comment] 2021-05-26 01:12
Duplicate of https://github.com/sass/sass/issues/3065.

**Closed by nex3** 2021-05-26 01:12 UTC
