### ISSUE TITLE
--watch flag not available 

### ISSUE THREAD

**Issue by Marvin-Tunji-ola** [sass/dart-sass#279] opened 2018-03-30 12:19 UTC
I installed sass yesterday with npm and tried running 

`sass --watch input.scss output.css`

but it returned 

     Could not find an option named "watch".
     
       Usage: sass <input> [output]

        --[no-]stdin                           Read the stylesheet from stdin.
        --[no-]indented                     Use the indented syntax for input from stdin.
        -I, --load-path=<PATH>       A path to use when resolving imports.
                                                      May be passed multiple times.
        -s, --style=<NAME>             Output style.
                                                      [expanded (default), compressed]

        -c, --[no-]color                      Whether to emit terminal colors.
        -q, --[no-]quiet                      Don't print warnings.
         --[no-]trace                           Print full Dart stack traces for exceptions.
         -h, --help                               Print this usage information.
         --version                                Print the version of Dart Sass.

Don't know if it's a Bug or it's no longer supported.

**Comment by nex3** [comment] 2018-03-30 21:11
Duplicate of #264. This will be supported, but it's not implemented yet.

**Closed by nex3** 2018-03-30 21:11 UTC

**Comment by north-krimsly-hp** [comment] 2018-04-16 21:45
Hi, I'm wondering what the easiest way is to get equivalent functionality for "sass --watch" with the new dart-sass? Otherwise, It isn't clear to me how I can automatically compile any number of .scss files within a folder. Sass is great but without --watch it's very hard and time consuming to use.

Thanks.

**Comment by nex3** [comment] 2018-04-19 20:43
For now you can use a build system like [Gulp](https://gulpjs.com/) or [Webpack](https://webpack.js.org/), or roll your own watcher using a package like [`chokidar`](https://www.npmjs.com/package/chokidar) or [`watchr`](https://www.npmjs.com/package/watchr). We're hard at work getting `--watch` and `--update` back online.
