### ISSUE TITLE
Error compiling `calc` with negative values at the end

### ISSUE THREAD

**Issue by ilunglee** [sass/dart-sass#1516] opened 2021-09-29 05:08 UTC
Hello there, 

I ran into an issue with `bootstrap@5.1.1` when compiling with `sass@1.42.1`.  Related to https://github.com/twbs/bootstrap/issues/35011

Here is the compilation error: 
```bash
Module build failed (from ./node_modules/postcss-loader/src/index.js):
ParserError: Syntax Error at line: 1, column 25
```

And, here are the lines that cause this issue:
```scss
 margin-top: calc(var(--#{$variable-prefix}gutter-y) * -1); // stylelint-disable-line function-disallowed-list 
 margin-right: calc(var(--#{$variable-prefix}gutter-x) * -.5); // stylelint-disable-line function-disallowed-list 
 margin-left: calc(var(--#{$variable-prefix}gutter-x) * -.5); /
```

The problem seems to be related to the negative values at the end of each line (e.g., `-1`, `-.5`). If I change the lines into the following, the compilation error no longer exists:
```scss
margin-top: calc(-1 * var(--#{$variable-prefix}gutter-y) * 1); // stylelint-disable-line function-disallowed-list
margin-right: calc(-1 * var(--#{$variable-prefix}gutter-x) * .5); // stylelint-disable-line function-disallowed-list
margin-left: calc(-1 * var(--#{$variable-prefix}gutter-x) * .5); // stylelint-disable-line function-disallowed-list
```

Thanks in advance for the assistance!

**Comment by jathak** [comment] 2021-09-29 20:47
Duplicate of #1496. This is a bug in `postcss-values-parser`, not Sass.

**Closed by jathak** 2021-09-29 20:47 UTC
