### ISSUE TITLE
Cannot compile any Sass (data or file)

### ISSUE THREAD

**Issue by NickRimer03** [sass/dart-sass#642] opened 2019-04-04 14:40 UTC
Hello there!
I'm trying to parse any sass using your module with no success.
I'm also using `webpack`.

```javascript
import sass from "sass";

const sassStr = `$colors: (red, green, blue);
$sizes: (
  big: 100,
  small: 50
);

@each $color in $colors {
  .#{$color} {
    background-color: $color;
  }
}

@each $size, $value in $sizes {
  .#{$size} {
    width: $value + px;
    height: $value + px;
  }
}`;

// sass.renderSync({ file: "./test.scss" });
sass.renderSync({ data: sassStr });
```

First of all I'm getting this warning in console:
```
WARNING in ./node_modules/sass/sass.dart.js 13:15-22
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

Than an error in browser console:
```
Uncaught Error: NoSuchMethodError: method not found: 'M' on null
```

Very interesting that using `file` property instead of `data` makes another error:
```
Uncaught Error: RangeError: Value not in range: 18
```

WAIDW? I just wanna the result of normal CSS. Your module seems to be the most alive and active.

**Comment by nex3** [comment] 2019-04-04 19:16
Duplicate of #25. Dart Sass doesn't currently support running in the browser.

**Closed by nex3** 2019-04-04 19:16 UTC
