### ISSUE TITLE
sass_api with JavaScript API?

### ISSUE THREAD

**Issue by niksy** [sass/dart-sass#1440] opened 2021-08-13 16:43 UTC
Are there any plans for JavaScript API for `sass_api` package?

I’ve tried compiling Dart version to JS with `dart2js` but I’m getting errors:

```
sass_api.js:4460 Uncaught TypeError: J.getInterceptor$s(...).get$codeUnits is not a function
    at Object.get$codeUnits$s (sass_api.js:4460)
    at Object.SourceFile$fromString (file.dart:62)
    at Object.SpanScanner$ (span_scanner.dart:63)
    at Object.Parser$ (parser.dart:52)
    at Object.Parser_parseIdentifier (parser.dart:32)
    at Object.main (sass_api.dart:30)
    at callMain (js_helper.dart:2684)
    at js_helper.dart:2684
    at js_helper.dart:2684
    at dartProgram (js_helper.dart:2684)
```

**Comment by jathak** [comment] 2021-08-18 20:16
Duplicate of https://github.com/sass/dart-sass/issues/88.

**Closed by jathak** 2021-08-18 20:16 UTC
