### ISSUE TITLE
`Uri.base` is not supported when running in a Deno environment.

### ISSUE THREAD

**Issue by LePichu** [sass/dart-sass#1841] opened 2022-12-11 20:32 UTC
# To Reproduce:
```ps1
$ deno run -A npm:sass index.scss
```
```sh
Unexpected exception:
Unsupported operation: 'Uri.base' is not supported


error: Uncaught UnsupportedError {
  message: "'Uri.base' is not supported",
  "$thrownJsError": Unsupported operation: 'Uri.base' is not supported
    at Object.wrapException (file:///C:/Users/Administrator/AppData/Local/deno/npm/registry.npmjs.org/sass/1.56.1/sass.dart.js:1247:17)
    at Object.Uri_base (file:///C:/Users/Administrator/AppData/Local/deno/npm/registry.npmjs.org/sass/1.56.1/sass.dart.js:5377:15)
    at Object.Style__getPlatformStyle (file:///C:/Users/Administrator/AppData/Local/deno/npm/registry.npmjs.org/sass/1.56.1/sass.dart.js:7576:13)
    at file:///C:/Users/Administrator/AppData/Local/deno/npm/registry.npmjs.org/sass/1.56.1/sass.dart.js:100867:68
    at Object.holder.<computed> [as $get$Style_platform] (file:///C:/Users/Administrator/AppData/Local/deno/npm/registry.npmjs.org/sass/1.56.1/sass.dart.js:258:21)
    at file:///C:/Users/Administrator/AppData/Local/deno/npm/registry.npmjs.org/sass/1.56.1/sass.dart.js:100863:92
    at Object.holder.<computed> [as $get$context] (file:///C:/Users/Administrator/AppData/Local/deno/npm/registry.npmjs.org/sass/1.56.1/sass.dart.js:258:21)
    at Frame.get$library (file:///C:/Users/Administrator/AppData/Local/deno/npm/registry.npmjs.org/sass/1.56.1/sass.dart.js:67137:16)
    at Frame.get$location (file:///C:/Users/Administrator/AppData/Local/deno/npm/registry.npmjs.org/sass/1.56.1/sass.dart.js:67153:20)
    at Trace_toString_closure0.call$1 (file:///C:/Users/Administrator/AppData/Local/deno/npm/registry.npmjs.org/sass/1.56.1/sass.dart.js:67500:20)}
```

# Expected Result:
This should have ran out of box, but it does not.

# Host:
OS: Windows 10
Arch: x86
Runtime: Deno

**Comment by nex3** [comment] 2022-12-12 21:24
Duplicate of https://github.com/sass/dart-sass/issues/1142

**Closed by nex3** 2022-12-12 21:24 UTC
