### ISSUE TITLE
\xxxxx characters are escaped

### ISSUE THREAD

**Issue by joneff** [sass/dart-sass#719] opened 2019-06-10 17:59 UTC
There have been numerous reports #79, #345, #485.

While I do agree that semantically `\1234` and `ሴ` are the same, it still makes a difference when we see the former in the output. My main concern is that private chars, like `\f000` or `\f0f0` are impossible to distinguish from one another when encoded (`` vs ``). That makes debugging and troubleshooting much harder.

I do understand the reasoning behind encoding, but shouldn't there be an option to disable it somehow?

I am also OK with using ugly hacks like `#{unquote('\\') + f0f0}` as long as I know that at some point those will not cease to work.

**Comment by nex3** [comment] 2019-06-11 15:02
Duplicate of https://github.com/sass/dart-sass/issues/568

**Closed by nex3** 2019-06-11 15:02 UTC
