### ISSUE TITLE
SASS fails to compile files under Jest

### ISSUE THREAD

**Issue by TheLonelyAdventurer** [sass/dart-sass#1692] opened 2022-05-14 19:06 UTC
Running `sass.compile(path)` wil throw a suspicious exception:

```
TypeError: J.getInterceptor$ax(...).map$1$1 is not a function

      at Object.map$1$1$ax (node_modules/sass/sass.dart.js:24596:44)
      at listDir_closure0.call$0 (node_modules/sass/sass.dart.js:87563:18)
      at Object._systemErrorToFileSystemException0 (node_modules/sass/sass.dart.js:20859:23)
      at Object.listDir0 (node_modules/sass/sass.dart.js:20854:16)
      at _realCasePath_helper_closure0.call$0 (node_modules/sass/sass.dart.js:85221:34)
      at JsLinkedHashMap.putIfAbsent$2 (node_modules/sass/sass.dart.js:27356:24)
      at _realCasePath_helper0.call$1 (node_modules/sass/sass.dart.js:85210:32)
      at _realCasePath_helper_closure0.call$0 (node_modules/sass/sass.dart.js:85217:35)
      at JsLinkedHashMap.putIfAbsent$2 (node_modules/sass/sass.dart.js:27356:24)
      at _realCasePath_helper0.call$1 (node_modules/sass/sass.dart.js:85210:32)
```

The code above was run using `jest`.

Basic code that reproduces the error:

```js
const sass = require('sass');

const config =
	{ sourceMap: false
	, sourceMapIncludeSources: false
	, style: 'compressed'
	, verbose: true
	, logger: console
	, alertAscii: false
	, alertColor: true
	, functions: {}
	, importers: []
	, loadPaths: []
	, quietDeps: true
	};


function compile() {
	return sass.compile('test.scss');
}

console.log(compile());
```

The exact same code works when run outside jest.

I've tracked down the compiled js of sass up to this line of sass.dart.js:

![immagine](https://user-images.githubusercontent.com/35636532/168445020-a37ed237-8ba2-4f9b-85d2-b7aa02de3a99.png)

which is called by:

![immagine](https://user-images.githubusercontent.com/35636532/168444976-4c1a0ca6-5ccd-42c5-94b3-700f57822ff4.png)

which is in turn called by:

![immagine](https://user-images.githubusercontent.com/35636532/168444946-ae62cd9b-a5bb-45fc-ac09-6bb6ec0c2d4f.png)

As expected these are the results in my debugger for checking the parameters:

![immagine](https://user-images.githubusercontent.com/35636532/168445052-bf764140-570c-4670-8474-e146105cd69b.png)

I am not sure what `map$1$1` is, but it seems to depend on the running environment as far as I understand the problem.

**Comment by akabekobeko** [comment] 2022-05-15 12:37
I have the same problem in my environment, if I run `sass.compile(path)` without Jest it works fine.

**Comment by jathak** [comment] 2022-05-16 20:36
Duplicate of #710.

**Closed by jathak** 2022-05-16 20:36 UTC

**Comment by akabekobeko** [comment] 2022-05-16 23:08
@jathak 
Specifying `testEnvironment: "node"` in `jest.config.js` does not solve the problem.
This value currently defaults to `node`, but an error will still occur if explicitly specified.

If deprecated, the explanation in #710 is not sufficient. Either #710 or the "recommended method" resolves the error, or should explicitly state in the README or API reference that execution by Jest is not supported.

**Comment by jathak** [comment] 2022-05-23 20:49
@akabekobeko @lfdebrux Does setting `testEnvironment` to `jest-environment-node-single-context` work? That's what we use [here](https://github.com/sass/sass-spec/blob/main/jest.config.ts#L6).

**Comment by akabekobeko** [comment] 2022-05-24 07:57
@jathak 
Thanks!
That way `sass.compile(path)` is now executable on Jest.

## Add npm

```
$ npm i -D jest-environment-node-single-context
```

## Config

```js
module.exports = {
  testEnvironment: 'jest-environment-node-single-context',
  verbose: true,
  testTimeout: 10000,
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
};
```

## Test on Jest

`transpileCss` calls `sass.compile(path)` internally.

```typescript
import { transpileCss } from './css';

it('Transpile SCSS', () => {
  const css = transpileCss('sass', './src2/data/scss/app.scss');
  const expected = `body {
  width: 100%;
  height: 100%;
  margin: 0;
  padding: 0;
  background-color: #fbfcfa;
}`;
  expect(css).toBe(expected);
});
```

Result

```
 PASS  src2/css.test.ts
  ✓ Transpile SCSS (55 ms)
```

**Comment by TheLonelyAdventurer** [comment] 2022-05-26 09:35
> 

I tried to use it, but fails with:

```
TypeError: The "options.context" property must be an vm.Context. Received an instance of Object
```

Could it be because I'm using Yarn with pnp modules?

**Comment by akabekobeko** [comment] 2022-05-26 10:02
@TheLonelyAdventurer 
I am running the tests with `npm test`, not using Yarn and the pnp module. The following PR is an actual successful example.

- [chore: Added test for AltCSS transpile by akabekobeko · Pull Request #17 · vivliostyle/vivliostyle-sitegen](https://github.com/vivliostyle/vivliostyle-sitegen/pull/17)

**Comment by TheLonelyAdventurer** [comment] 2022-05-26 10:11
@akabekobeko yeah it's probably a specific issue with Yarn

**Comment by mizdra** [comment] 2022-08-27 16:09
I found another workaround. This method also works for `testEnvironment: 'node'`.

Here is the tricks:
- Disguise the test environment as a browser and bypass https://github.com/dart-lang/sdk/issues/47670
  - For some reason, https://github.com/dart-lang/sdk/issues/47670 does not occur in the browser environment :)
- When compiling sass, we pass our own importer
  - If you disguise as a browser, dart-sass will use the browser's path resolution algorithm to resolve the path.
  - This will result in a runtime error.
  - So, we pass an importer that implements the Node.js path resolution algorithm.

The following PR is an actual successful example.
https://github.com/mizdra/checkable-css-modules/pull/76/commits/a42397b49cd4beb55d6a6e1b9a586e9dd29ae1ef

**Comment by TheLonelyAdventurer** [comment] 2022-09-08 11:39
> > 
> 
> I tried to use it, but fails with:
> 
> ```
> TypeError: The "options.context" property must be an vm.Context. Received an instance of Object
> ```
> 
> Could it be because I'm using Yarn with pnp modules?
> 
> Reported in [kayahr/jest-environment-node-single-context#10](https://github.com/kayahr/jest-environment-node-single-context/issues/10)



> @TheLonelyAdventurer I am running the tests with `npm test`, not using Yarn and pnp module. The following PR is an actual successful example.
> 
>     * [chore: Added test for AltCSS transpile by akabekobeko · Pull Request #17 · vivliostyle/vivliostyle-sitegen](https://github.com/vivliostyle/vivliostyle-sitegen/pull/17)

Update: the package also fails with yarn1 and NPM. I guess there is an issue with node modules.
