### ISSUE TITLE
loadedUrls/includedFiles not returned on error

### ISSUE THREAD

**Issue by mischnic** [sass/dart-sass#1584] opened 2022-01-01 13:14 UTC
When some error happens during parsing or compilation, the list of included files isn't returned.

This is causing problems for Parcel because the sass file that caused the error isn't watched.

So maybe either a `loadedUrls` property on the error object, or no actually throwing an error but instead returning some error result object

**Comment by nex3** [comment] 2022-01-04 21:32
Duplicate of https://github.com/sass/sass/issues/2950

**Closed by nex3** 2022-01-04 21:32 UTC
