### ISSUE TITLE
Feature request: passing all module variables in another module

### ISSUE THREAD

**Issue by Kroid** [sass/dart-sass#1003] opened 2020-05-12 13:06 UTC
What do you think about passing all module variables in another module?

For example, something like that:

```scss
//_mixins.scss
$background-color: black !default;
$color: red !default;
$font-size: 12px !default;

@mixin demo {
  background-color: $background-color;
  color: $color;
  font-size: $font-size;
}
```

```scss
//_myvars.scss
$color: blue !default;
$font-size: 18px !default;
```

```scss
//style.scss
@use "myvars";
@use "mixins" with (myvars.*)

h1 {
  @include mixins.demo;
}
```

will compile to:

```css
h1 {
  background-color: black;
  color: blue;
  font-size: 18px;
}
```

**Comment by Awjin** [comment] 2020-05-13 20:33
Duplicate of #2846—in particular https://github.com/sass/sass/issues/2846#issuecomment-618042396

**Closed by Awjin** 2020-05-13 20:33 UTC

**Comment by Awjin** [comment] 2020-05-13 21:29
In general, `@use ... with` isn't meant to handle advanced use cases. I'd recommend taking a look at https://sass-lang.com/documentation/at-rules/use#with-mixins for alternatives.
