### ISSUE TITLE
`SassCalculation` is not exposed in JS API

### ISSUE THREAD

**Issue by niksy** [sass/dart-sass#1688] opened 2022-05-06 07:35 UTC
[`SassCalculation` type is exposed in Dart API](https://github.com/sass/dart-sass/blob/1e211d640a86160910a53de600e3a55f70409470/CHANGELOG.md#dart-api-2), but I can’t see it inside JS API.

Is there any reason why it isn’t exposed?

**Comment by nex3** [comment] 2022-05-10 20:33
Duplicate of https://github.com/sass/sass/issues/818. This is the last chunk of first-class calc support that has yet to be implemented.

**Closed by nex3** 2022-05-10 20:33 UTC

**Comment by niksy** [comment] 2022-05-11 05:57
@nex3 Oh wow, haven’t seen this issue, otherwise I wouldn’t open this one! Do you maybe know when will this be available in JS API?

**Comment by nex3** [comment] 2022-05-16 20:54
We don't have any concrete timeline for it at the moment. If it's important to you, we'd love to have your help :).

**Comment by niksy** [comment] 2022-05-17 05:58
Where do we start? Should we use reference from other already implemented features or? Original issue is almost 10 years old :D

**Comment by nex3** [comment] 2022-05-23 21:48
I recommend taking a look at existing JS API proposals, like [this one for adding the logger API](https://github.com/sass/sass/blob/main/accepted/js-logger.d.ts) and using that as the template. The [contributing file](https://github.com/sass/sass/blob/main/CONTRIBUTING.md) also has guidelines on how to write a good specification.
