### ISSUE TITLE
Feature request: opt-in to new “mixed declarations” behavior without adding & { }

### ISSUE THREAD

**Issue by controversial** [sass/dart-sass#2401] opened 2024-10-22 19:01 UTC
I understand that the way Sass emits nested rules/declarations will change in a future major release to match CSS, that this will be a breaking change, that deprecation warnings are in place to warn about this change, and that I can silence the deprecation warnings.

The docs currently recommend that the best way to opt in to the new behavior is to add `& { }` around every declaration that appears after a nested rule. However, in large code bases this may require hundreds of individual changes, may increase the verbosity of code substantially, and may do so in a way that’s hard to remember to change *back* after the 2.0.0 release.

Instead of wrapping all our code in `& { }`, is it possible that sass could add to the cli / api **an option that would opt *in* to the new behavior everywhere**? 
- This wouldn’t be a breaking change because it would require opt-in
- This would allow developers to test their code early under the new behavior (without waiting for any other components of the upcoming 2.x release, waiting for ecosystem packages to update peer dependencies, etc.)
- This would be an easy way for authors to accept the risks and silence the deprecations in codebases where the authors are reasonably confident their “mixed declarations” aren’t order-sensitive with respect to the nested rules.

**Comment by nex3** [comment] 2024-10-22 19:22
Duplicate of https://github.com/sass/sass/issues/3960

**Closed by nex3** 2024-10-22 19:22 UTC
