### ISSUE TITLE
support a custom resolver/importer in JS build

### ISSUE THREAD

**Issue by graingert** [sass/dart-sass#171] opened 2017-09-06 13:25 UTC
This is required for webpack's sass-loader: https://github.com/webpack-contrib/sass-loader/issues/435#issuecomment-327480177

> But main problem is dart-sass don't support custom importer, without this feature, it is impossibly to implement support dart-sass in sass-loader.

**Comment by nex3** [comment] 2017-09-29 22:50
Duplicate of #9.

**Closed by nex3** 2017-09-29 22:50 UTC
