### ISSUE TITLE
A selector is missing after compile (mixin)

### ISSUE THREAD

**Issue by kna** [sass/dart-sass#1588] opened 2022-01-05 04:23 UTC
`@mixin` prevents a selector exported.
It does not happen with libsass. 

input:
```
%p1 {
  :lang(en) & {
    color: white;
  }
}

@mixin m1($base: 'a') {
  .z .#{$base} {
    .c {
      @extend %p1;
    }
  }
}

@include m1('a');

.z .a.b {
  .c {
    @extend %p1;
  }
}
```

output(libsass v3.5.5 on [sassmeister](https://www.sassmeister.com/)):
```
:lang(en) .z .a .c, .z .a :lang(en) .c, :lang(en) .z .a.b .c, .z .a.b :lang(en) .c {
  color: white;
}
```

output(dart-sass v1.32.12 on [sassmeister](https://www.sassmeister.com/), dart-sass cli v1.45.2):
```
:lang(en) .z .a .c, .z .a :lang(en) .c {
  color: white;
}
```

This might be related to https://github.com/sass/dart-sass/issues/1587

**Comment by stof** [comment] 2022-01-05 12:24
This indeed looks like a duplicate of #1587, as it is also about extending a placeholder selector with a case involving a superselector (`.a` vs `.a.b`)

**Closed** 2022-01-05 21:30 UTC
