### ISSUE TITLE
features request 

### ISSUE THREAD

**Issue by spicestudio** [sass/dart-sass#1720] opened 2022-06-14 04:49 UTC
Hi i want some new features like documentation (you can use docusarus)
new features like conditional import, autoprefixer , JIT complier , official Vscode extensions with full intellisense
and a variable will called compress takes a Boolean and at compile every class has the same property take it like extend at rule it's very useful for components
@apply directive like in tailwind

**Comment by nex3** [comment] 2022-06-15 01:43
Duplicate of https://github.com/sass/sass/issues/3331

Please don't open the same issue in multiple repositories.

**Closed by nex3** 2022-06-15 01:43 UTC
