### ISSUE TITLE
CLI watch not working correctly

### ISSUE THREAD

**Issue by gustavo-candido** [sass/dart-sass#964] opened 2020-02-27 23:55 UTC
Lets try to make this square green instead red.  

![image](https://user-images.githubusercontent.com/39497287/75496624-80470980-59a0-11ea-9b4f-ea4fa80faa8b.png)

When just update the variable value and refresh all sass didn't recompile the file
![image](https://user-images.githubusercontent.com/39497287/75496757-f9def780-59a0-11ea-849b-3ff11b2efb3d.png)

But if i do something like a compile error, save, fix the error and save all works

![image](https://user-images.githubusercontent.com/39497287/75496985-9608fe80-59a1-11ea-9eee-25f42561c3e3.png)

![image](https://user-images.githubusercontent.com/39497287/75497007-a4571a80-59a1-11ea-90df-acf667ee8e17.png)

I'm using W10,  SASS 1.25.0 compiled with dart2js 2.7.0 and IDE ST3 and Visual Studio

**Comment by nex3** [comment] 2020-02-28 02:09
This may have been fixed by the fix for #550, which was released in Sass 1.26.1. Please try that and see if it still reproduces.

If you're still seeing the issue, I'll need you to put together a reproduction for me. Ideally this would be [a test case](https://github.com/sass/dart-sass/blob/master/test/cli/shared/watch.dart) that demonstrates the issue, which you can submit as a pull request. If you're not comfortable doing that, a step by step guide for reproducing this from scratch using only the command line would work as well.

**Comment by gustavo-candido** [comment] 2020-02-28 03:14
Quick try to update but not sucess and now the hack of introduce a bug and fix dont work anymore. Its a little late now in Brazil but I will try to send you the pull request has much as possible. Thanks for answering

**Comment by freethebit** [comment] 2020-03-13 17:15
I had a similar problem @gustavo-candido , but on ubuntu, it was fixed on Sass 1.26.1. The only thing i like to point is, make sure the browser's cache is completely disabled, this is where I also got some trouble.

**Comment by nex3** [comment] 2020-11-12 00:47
Closing this out since there's been no info about how to reproduce.

**Closed by nex3** 2020-11-12 00:47 UTC
Labels: CLI, bug, needs info
