### ISSUE TITLE
Module names that start with numbers cause compilation errors

### ISSUE THREAD

**Issue by jackson-mastery** [sass/dart-sass#1225] opened 2021-02-03 14:30 UTC
The Dart compiler appears to have trouble with modules that start with numeric characters. My ideal file structure would look like this:
```
01_settings/
  _some_settings.scss
  _design_tokens.scss
  _index.scss
02_normalize/
  _our_normalize.scss
  _index.scss
...
main.scss
```

The intent is to write the lowest specificity styles in `01_settings` and gradually increase specificity as the directory numbers increase. Ideally the directory numbers would help illustrate that, and help other people on my team contribute or understand the project a little quicker if they're new. 

However, any modules that start with numeric characters seem to cause errors when compiling. Small reproduction:
```
// 01_settings/_design-tokens.scss
$logo-dark: #e2383f;
$logo-middle: #ec8170;
$logo-light: #f6c0b2;
```

```
// 01_settings/_index.scss
@use 'design-tokens'
```

```
// main.scss
@use '01_settings';
```

Outputs:
```
Error: Invalid Sass identifier "01_settings"
   ╷
16 │ @use '01_settings';
   │ ^^^^^^^^^^^^^^^^^^
   ╵
```

Changing the directory name (and all the appropriate `@use` commands) from `01_settings` to `a01_settings` stops the error. 

If this is intended behavior then I can figure out another approach, but something should be added to the documentation stating so.

**Comment by Awjin** [comment] 2021-02-03 20:57
Duplicate of https://github.com/sass/dart-sass/issues/1099

**Closed by Awjin** 2021-02-03 20:57 UTC
