### ISSUE TITLE
Segmentation fault in Dart 2.13.1 in Dart Sass 1.34.1, 1.34.0, but not in 1.32.10

### ISSUE THREAD

**Issue by bpilot** [sass/dart-sass#1345] opened 2021-06-04 04:44 UTC
dart --version
Dart SDK version: 2.13.1 (stable) (Unknown timestamp) on "linux_x64"

pubspec.yaml:
environment:
  sdk: '>=2.12.0 <3.0.0'

Code:
String assetContents = sass.compile(path.join(assetsPath, fileName), loadPaths: [assetsPath]);

Error from VM:
===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x5600a72334d0
version=2.13.1 (stable) (Unknown timestamp) on "linux_x64"
pid=1086295, thread=1086303, isolate_group=main(0x55f8a9984300), isolate=main(0x55f8a99bee00)
isolate_instructions=55f8a73fc020, vm_instructions=55f8a73fc020
Stack dump aborted because GetAndValidateThreadStackBounds failed.
Aborted (core dumped)

This happens in Dart Sass 1.34.1 and 1.34.0.

It doesn't happen in 1.32.10, so appears to be a newer regression.

Probably is caused by the Sass input code somewhere, but I don't know where, unfortunately.

I know this is probably not enough information to actually debug this, but I'm hoping that combined with other clues, this will help figure out where the regression is.

**Comment by jathak** [comment] 2021-06-04 20:23
Can you provide a reproduction repo? It's hard to debug what's going on here without knowing `assetsPath` or what's in it.

**Comment by bpilot** [comment] 2021-06-08 00:17
There's loads of Sass files, unfortunately. I'm thinking it might be best if I can get it to print out exactly which file it is processing, if that is possible.

**Comment by jathak** [comment] 2021-06-09 20:58
We're not going to be able to help debug without a reproduction, but if you'd like to look into it yourself, you could try cloning the dart-sass repo and adding some debugging print statements to try to narrow down the cause.

Ultimately though, a segmentation fault is a bug in the Dart VM, not in Sass, so you should file a bug against the Dart SDK. I'm going to close this for now.

**Closed by jathak** 2021-06-09 20:58 UTC
Labels: needs info
