### ISSUE TITLE
Error compiling bootstrap glyphicon, and font-awesome.

### ISSUE THREAD

**Issue by yanivkalfa** [sass/dart-sass#345] opened 2018-06-05 09:22 UTC
I am trying to compile bootstrap-sass or font-awesome-sass to normal css. The fonts are being added correctly however the '::after -> content ' attribute is messaged up completely. 

To check that its not on my end, I took the content of a working icon, and pasted it instead of the content that your compiler produced and it works fine.

**Comment by nex3** [comment] 2018-06-05 18:27
Can you provide a concrete example of Sass code that compiles as expected in Ruby Sass and not in Dart Sass?

**Comment by yanivkalfa** [comment] 2018-06-05 19:17
https://github.com/yanivkalfa/react-redux-immutable-router-localization/blob/icons-test/src/app/containers/Home/index.js

This repository for example uses node-sass/sass-loader. the compiled css for glyphicons are correct.
eg: 'glyphicon-arrow-right:before{content:"\E092"}'

Take this little icon test repo:
https://github.com/yanivkalfa/icon-test
npm run test
look at the created style.css
and look for : 'glyphicon-arrow-right'
You'll see that the content is wrong.

**Comment by nex3** [comment] 2018-06-05 23:21
I'm looking for a stand-alone reproduction: just plain Sass code, the CSS you expect to be generated, and the CSS that's actually generated.

**Comment by yanivkalfa** [comment] 2018-06-06 17:49
@nex3 the second repo: `https://github.com/yanivkalfa/icon-test` is a stand-lone reproduction of the error...

Very simple sass to css

**Comment by nex3** [comment] 2018-06-06 18:44
It's not standalone; it imports a file from bootstrap.

**Comment by yanivkalfa** [comment] 2018-06-06 20:35
I see, well I am not sure how else I could farther assist you. something is going wrong there that produces incorrect css by compiling a scss bootstrap file.

The above example show you how to reproduce it without doing anything fancy. meanwhile i moved to another structure to workaround the problem.

If you have any question I will be happy to answer.

**Comment by nex3** [comment] 2018-06-06 21:38
I'm going to close this pending a standalone test case.

**Closed by nex3** 2018-06-06 21:38 UTC
Labels: needs info

**Comment by yanivkalfa** [comment] 2018-06-06 22:32
@nex3 https://github.com/yanivkalfa/icon-test i've made it even simpler - now is just take the string `.glyphicon-arrow-left { &:before { content: "\e091"; } }` in a file and compiled it.

**Comment by yanivkalfa** [comment] 2018-06-07 18:21
@nex3 
after checking a little farther - this error doesn't happened when you use "data"

```javascript
const sass = require('sass');

const result = sass.renderSync({ data: '.glyphicon-arrow-left { &:before { content: "\e091"; } }' });
console.log(result.css.toString()); - will produce the right output.
```

However

```javascript
const result = sass.renderSync({ file: path_to_file });
console.log(result.css.toString());
```

Will not.

**Comment by nex3** [comment] 2018-06-09 00:19
Dart Sass does compile CSS escapes to literal Unicode values--that is, it generates `content: ""` rather than `content: "\e091"`. I believe Node Sass does not do this, so perhaps that's the difference you're seeing. However, the CSS spec declares that these representations are identical, and as far as I've ever seen no browsers render them differently (assuming the browser reads your CSS as UTF-8).

Your `data:` example is broken; the backslash is interpreted by JavaScript, not by Sass, and so it generates `content: "e091"` without a backslash at all. If you escape the backslash, the output is the same.

**Comment by yanivkalfa** [comment] 2018-06-09 02:41
@nex3 I was using Chromium 61.0.3163.1. haven't tested any other browsers. either way. thanks for responding and good luck with the project.

**Comment by nex3** [comment] 2018-06-09 18:21
[This pen](https://codepen.io/nex3/pen/XYpaVE) uses both an escape code and a literal Unicode character, and renders two identical snowmen for me on Chrome 67.0.3396.79 and Firefox 52.6.0.

**Comment by N6REJ** [comment] 2019-01-22 20:52
is there anyway to force uft-8 output?

**Comment by nex3** [comment] 2019-01-24 01:03
@N6REJ I'm not sure what you mean by that. Sass always emits UTF-8.

**Comment by N6REJ** [comment] 2019-01-25 03:14
@nex3 sorry it does not.. if you run ruby based sass on scss you'll get unicode output, if you run js npm-sass you'll get utf-8

**Comment by nex3** [comment] 2019-01-25 03:41
I'm not sure what the difference between "unicode output" and "utf-8" is, and I don't know whether "js npm-sass" refers to the [`node-sass` package](https://npmjs.com/package/node-sass) or the [`sass` package](https://npmjs.com/package/sass).

**Comment by N6REJ** [comment] 2019-01-25 05:43
ok, I"m probably confusing us both since This is my first time trying to use scss....
IF I use a ruby based scss compressor, then as you stated it output unicode. so you don't get \e091 in your *.css file.  you get  content: ""
IF, I use node-sass ( which I understand uses js instead of ruby ) then I do get content: "e091" as desired...
While they may function the same ( idk ) I don't want obscure non-readable chars in my output.

**Comment by nex3** [comment] 2019-01-25 22:36
What you're looking for is an escape code rather than a UTF-8 character. #568 tracks adding a flag to force all non-ASCII characters to be emitted as escape codes.

**Comment by N6REJ** [comment] 2019-01-26 07:32
> Dart Sass does compile CSS escapes to literal Unicode values--that is, it generates `content: ""` rather than `content: "\e091"`. I believe Node Sass does not do this, so perhaps that's the difference you're seeing. However, the CSS spec declares that these representations are identical, and as far as I've ever seen no browsers render them differently (assuming the browser reads your CSS as UTF-8).
> 
> Your `data:` example is broken; the backslash is interpreted by JavaScript, not by Sass, and so it generates `content: "e091"` without a backslash at all. If you escape the backslash, the output is the same.

Thats not what you stated here.  Please stop giving me the run around.

**Comment by nex3** [comment] 2019-01-29 00:42
@N6REJ Please follow the [Sass community guidelines](http://sass-lang.com/community-guidelines), particularly to assume good intentions from people you interact with.
