### ISSUE TITLE
Space between value and unit in function output

### ISSUE THREAD

**Issue by scheibome** [sass/dart-sass#1064] opened 2020-08-26 12:20 UTC
In Node-sass I have written the following function, which `.title { font-size: 1.875rem; }` returns.

With dart-sass I have with the same function a bookmark between value and unit. So `.title { font-size: 1.875 rem; }` is this a bug or am I doing something wrong?

**My code:**

```
$baseSize: 16;

@function em($pixels, $context: $baseSize, $lengthSpecification: rem) {
  @if (unitless($pixels)) {
    $pixels: $pixels * 1px;
  }

  @if (unitless($context)) {
    $context: $context * 1px;
  }

  @return ($pixels/$context*1)#{$lengthSpecification};
}

.title{
  font-size: em(30px);
}
```

**Comment by Awjin** [comment] 2020-08-26 16:28
Duplicate of https://github.com/sass/dart-sass/issues/1008.

**Closed by Awjin** 2020-08-26 16:28 UTC
