### ISSUE TITLE
Sass compiles VERY slowly since `v1.59` (8 times slower than `v1.58`)

### ISSUE THREAD

**Issue by Elysiome** [sass/dart-sass#1913] opened 2023-03-13 14:17 UTC
# Introduction

Hi,

I've just migrated from `v1.58.3` to `v1.59.2`, and since, Sass compiles **VERY VERY VERY** slowly. It worked fast under `v1.58.3`. My Node.js is `v18.14.2`.

| Sass version | Node.js version | Compilation time |
| :----------: | :-------------: | :---------: |
|   `1.58.3`   |   `18.14.2`    |     28 seconds      |
|   `1.59.2`   |   `18.14.2`    |     3 minutes and 55 seconds      |

Has anyone encountered a similar issue? Thanks. 👍

# Scenario

I'm using the JavaScript API of Sass through https://github.com/dlmanning/gulp-sass.

# Screenshots

 `v1.58.3`:

![v1 58 3](https://user-images.githubusercontent.com/59090546/224739015-3d307a15-afd1-4dd3-8995-8fb283cf20f7.png)

 `v1.59.2`:

![v1 59 2](https://user-images.githubusercontent.com/59090546/224739040-65b859b6-ca4b-4898-abdb-151b54c3592b.png)

**Comment by flannanl** [comment] 2023-03-13 14:51
I'm seeing the same issue after moving up to `1.59`. I am running the `sass` command directly and my node version is `18.15.0`.

**Comment by jlenos** [comment] 2023-03-13 15:07
My Sass is erroring out with 1.59+

```
.../node_modules/sass/sass.dart.js:19
self.exports = _cliPkgExportParam ?? exports;
                                   ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    ...
```

**Comment by s100** [comment] 2023-03-13 16:02
+1 to this issue. In our case the previous compile time was a few seconds, but now it's 15 minutes plus, long enough for our builds to start timing out. I am attempting to put together a minimal reproduction of the problem - as in, a stylesheet which compiles quickly under 1.58 but slowly under 1.59 - but our CSS is very complicated and pulls in a lot of third-party styles, so it's taking me some time. I am guessing that this was introduced under https://github.com/sass/dart-sass/pull/1903/files but that is only a guess. This *doesn't* seem to be anything to do with repeated SCSS module loading - so far my minimal stylesheet is just one (extremely long) file, with no `@import`s.

Something I have noticed is that we make extensive, repeated use of this pattern:

```css
  .#{$prefix}--data-table--short thead tr,
  .#{$prefix}--data-table--short tbody tr,
  .#{$prefix}--data-table--short tbody tr th {
    height: rem(32px);
  }
```

, we have `$prefix: 'bx'` earlier in the CSS. If I inline that variable, making:

```css
  .bx--data-table--short thead tr,
  .bx--data-table--short tbody tr,
  .bx--data-table--short tbody tr th {
    height: rem(32px);
  }
```

then compile time seems to drop back to normal.

**Comment by TopGrd** [comment] 2023-03-14 12:54
>  long enough for our builds to start timing out

same with me

**Comment by jathak** [comment] 2023-03-14 17:41
Currently working on investigating this.

Just to check, is everyone here using the JS-compiled version of Sass (the NPM `sass` package), or is anyone using the Dart VM binary (either directly through the standalone releases, or via the `sass-embedded` NPM package)?

**Comment by flannanl** [comment] 2023-03-14 17:45
I'm using NPM sass too

**Comment by ntkme** [comment] 2023-03-14 18:24
> Currently working on investigating this.
> 
> Just to check, is everyone here using the JS-compiled version of Sass (the NPM `sass` package), or is anyone using the Dart VM binary (either directly through the standalone releases, or via the `sass-embedded` NPM package)?

I can confirm the same regression with dart-sass-embedded with interpolation in selector.

**Comment by ntkme** [comment] 2023-03-14 18:57
CPU Flame Chart
<img width="1920" alt="Screenshot 2023-03-14 at 11 55 54 AM" src="https://user-images.githubusercontent.com/899645/225109174-5984639c-0278-43a1-9c50-8d0a2527a486.png">

**Comment by jathak** [comment] 2023-03-14 21:37
The latest version of Dart Sass (1.59.3) should fix this from the tests I've run on both Node and the Dart VM, so please let me know if you're still encountering performance issues on 1.59.3 that weren't present on 1.58.x.

**Comment by ntkme** [comment] 2023-03-14 22:01
@jathak

- Each call to `InterpolationMap.mapSpan` results in 2 calls to `FileSpan.getText` (one for left and one for right).
- In 1.59.2 `InterpolationMap.mapSpan` is called 4 times for a single interpolation, meaning 8 calls to `FileSpan.getText`.
- In 1.59.3 `LazyFileSpan` is introduced so that we no longer call `FileSpan.getText` unless an exception is thrown or sourceMap is requested.
  - If sourceMap is requested, we still have 2 calls to `FileSpan.getText` for each interpolation... I confirmed this via CPU profiling. I think this is where @Elysiome is seeing 4x improvement (8 calls becomes 2 calls) but it is still a regression.

**Comment by ntkme** [comment] 2023-03-14 22:30
If we want to fix the regression without reverting the feature, we probably have to improve the performance of `FileSpan.getText` itself, or find a way to scan/seek the underneath buffer directly and bypass the weird String/List operations that `FileSpan.getText` does.

**Comment by jathak** [comment] 2023-03-14 23:17
Right, I forgot about source maps. I can think of a few possibilities that could speed things up on the margins, but I think it  makes sense to wait until Natalie gets back on Monday to discuss with her about any more complicated changes here.

In the meantime, @Elysiome, given your compilation was already taking 28 seconds before this change, you may want to consider using the [`sass-embedded` package](https://www.npmjs.com/package/sass-embedded) instead of `sass`. It should be a drop-in replacement, and the [speedup you get from running on the Dart VM instead of via Node](https://github.com/sass/dart-sass/blob/main/perf.md) could cancel out the slowdown here (and once we do improve it further, you'll get an even faster build than you had previously).

**Comment by ntkme** [comment] 2023-03-14 23:47
> But I have to install Dart in order for sass to work, right?

The Dart VM is embedded in the npm package.

**Comment by ntkme** [comment] 2023-03-15 00:55
While sass-embedded is designed as a drop-in replacement, performance wise there are a few caveats:

1. Do you know if your code is using legacy JS API (e.g. `render` or `renderSync`) or new JS API (e.g. `compile` or `compileSync`)? In sass-embedded the legacy API is emulated and have a huge performance impact if input files (including all dependencies) are large. Switching to the new JS API will improve it by a lot (to a degree that `sass-embedded` should  be almost always faster for large compilation requests).

2. Also, in `sass`, `sync` methods are faster than `async`, but in `sass-embedded`, it is the other way around that `async` methods are significantly faster than `sync` methods.

3. `sass-embedded` will suffer if you have lots of different entry points, this has been improved by https://github.com/sass/embedded-host-node/pull/207, but still the cost is not zero.

Related performance issues:
- https://github.com/sass/embedded-host-node/issues/109
- https://github.com/sass/sass/issues/3296
- https://github.com/sass/dart-sass-embedded/issues/112

**Comment by ntkme** [comment] 2023-03-15 01:10
> By the way, do you have any idea for the `1.` point describing an error during an import? Does the import works differently between `sass` and `sass-embedded`?

I suspect there are some inconsistency in sass-embedded's legacy API emulation with the sass' implementation.

**Comment by s100** [comment] 2023-03-16 10:28
As of `sass@1.59.3`, our build is now running to completion in a perfectly timely fashion. I see that a few other people are still reporting performance regressions, but from our perspective this is fixed now. Thank you very much for your prompt response to this issue!

**Comment by nex3** [comment] 2023-03-20 21:49
I'm going to re-open this as I look into a way to handle this even if spans are eagerly materialized. https://github.com/dart-lang/source_span/pull/93 should allow us to expand these spans without allocating a bunch of large strings.

**Comment by alexander-xyz** [comment] 2023-04-04 17:19
I use native dart sass for compilation big sass file. If I use  --embed-source-map it compiles VERY slowly since from version 1.59.0, up to 1.60.0. Version 1.58.3 comile it in 1.5 sec, version 1.60.0 - 13 sec. Without source maps speed almost the same (but little bit longer maybe just for 100ms)

**Comment by kerryj89** [comment] 2023-04-04 22:13
Can confirm that there's a noticeable slowdown as I finally upgraded from 1.45.1 to 1.60.0 today.  I am running sass-cli to compile my Sass (one entrypoint file and --style expanded --load-path option pointed to node_modules). Compile went from around 5s to 1min 20s.

 Downgrading to 1.58.3 brought it back down to 5s.  The next version that I could install (1.59.1) took 7min 30s to compile.  So while the latest version is drastically better than 1.59.1 was, it is still drastically slower than 1.58.3.

I am using Node v16.17.0.  Going to downgrade to 1.58.3 for now.

**Closed** 2023-04-06 21:44 UTC

**Comment by nex3** [comment] 2023-04-06 21:46
1.61.0 is releasing which _should_ fix this issue. If you're still running into performance issues relative to 1.58, please provide a minimal reproduction that shows off the bad performance and I'll take another look at it.
