### ISSUE TITLE
Option to fail compilation on warn

### ISSUE THREAD

**Issue by alecgibson** [sass/dart-sass#1369] opened 2021-06-21 11:36 UTC
In projects with large build-chains, Sass warnings can sometimes get lost in a vast amount of logs.

It would be nice to have a strict build option, which fails Sass compilation if any warnings are encountered, so that this can be enabled in CI environments to bring more attention to these warnings.

**Comment by jathak** [comment] 2021-06-21 20:08
Duplicate of #633.

**Closed by jathak** 2021-06-21 20:08 UTC
