### ISSUE TITLE
Problem since 1.40.0 with bootstrap 5

### ISSUE THREAD

**Issue by kris2kris** [sass/dart-sass#1496] opened 2021-09-21 04:39 UTC
Hello, 

The following code of bootstrap produce a build error since sass 1.40.0 (https://github.com/twbs/bootstrap/blob/main/scss/mixins/_grid.scss)
```
margin-top: calc(var(--#{$variable-prefix}gutter-y) * -1); // stylelint-disable-line function-disallowed-list
margin-right: calc(var(--#{$variable-prefix}gutter-x) * -.5); // stylelint-disable-line function-disallowed-list
margin-left: calc(var(--#{$variable-prefix}gutter-x) * -.5); // stylelint-disable-line function-disallowed-list
```
If I remove the minus sign before 1 or .5 it works. I'm not sure that multiplication should failed because of a minus sign.

**Comment by yudielcurbelo** [comment] 2021-09-21 14:55
Same here.

**Comment by nex3** [comment] 2021-09-21 21:38
I can't reproduce this with Dart Sass 1.42.0:

```scss
a {
  $variable-prefix: foo-;
  margin-top: calc(var(--#{$variable-prefix}gutter-y) * -1); // stylelint-disable-line function-disallowed-list
  margin-right: calc(var(--#{$variable-prefix}gutter-x) * -.5); // stylelint-disable-line function-disallowed-list
  margin-left: calc(var(--#{$variable-prefix}gutter-x) * -.5); // stylelint-disable-line function-disallowed-list
}
```

This produces:

```css
a {
  margin-top: calc(var(--foo-gutter-y) * -1);
  margin-right: calc(var(--foo-gutter-x) * -0.5);
  margin-left: calc(var(--foo-gutter-x) * -0.5);
}
```

as expected.

What version of Sass are you using? Can you provide a minimal stylesheet that reproduces the issue?

**Comment by kris2kris** [comment] 2021-09-22 05:09
Hello @nex3 
I tried with all versions from 1.40.0 to 1.42.0

For my test,
- I create an app with create-react-app
- I add bootstrap 5.1.1 and sass 1.42.0
- import bootstrap in a .scss file

This is the package.json file 
```
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "web-vitals": "^1.0.1",
    "bootstrap": "5.1.1",
    "sass": "1.42.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Comment by bradbajuz** [comment] 2021-09-22 12:59
Still having the issues with sass 1.42.1 and boostrap 5.1.1. Had to fall back to sass 1.39.2 to be able compile bootstrap 5.1.1

**Comment by maicol07** [comment] 2021-09-22 15:22
I have the same issue with [mwc checkbox](https://github.com/material-components/material-web/tree/master/packages/checkbox):
```
PS C:\Users\Maicol\Documents\Progetti\Web\osm_rewrite> sass node_modules\.pnpm\@material+checkbox@12.0.0\node_modules\@material\checkbox\_checkbox-theme.scss
Error: Expected "(" or ".".
    ╷
329 │   $checkbox-padding: calc((_ripple-size - _icon-size) / 2);
    │                                        ^
    ╵
  node_modules\.pnpm\@material+checkbox@12.0.0\node_modules\@material\checkbox\_checkbox-theme.scss 329:40  root stylesheet
```

**Comment by stof** [comment] 2021-09-24 07:46
@maicol07 What are you expected to get for `_ripple-size` ? If you expect to use a variable, it misses a `$`.

**Comment by maicol07** [comment] 2021-09-24 07:47
> @maicol07 What are you expected to get for `_ripple-size` ? If you expect to use a variable, it misses a `$`.

That's not a file of mine. It's a file of MWC checkbox (a library I use in my project)

**Comment by stof** [comment] 2021-09-24 08:12
Well, if I look at the `_checkbox-theme.scss` file in the link you gave, it does **not** contain that source code at all...

**Comment by maicol07** [comment] 2021-09-24 08:17
Yes, you're right, because that file belongs to a dependency of mwc checkbox: mdc checkbox.

Here is the related lines:

[https://github.com/material-components/material-components-web/blob/65084baffaca256dd9eb77aae8fbafd379d8da00/packages/mdc-checkbox/_checkbox-theme.scss#L329](https://github.com/material-components/material-components-web/blob/65084baffaca256dd9eb77aae8fbafd379d8da00/packages/mdc-checkbox/_checkbox-theme.scss#L329)

**Comment by stof** [comment] 2021-09-24 08:33
@maicol07 and they already fixed the issue in their code (but they haven't released it yet) when they were intended to use a string containing a template for a `calc()` for their JS code instead of a valid CSS calc computation.

**Comment by maicol07** [comment] 2021-09-24 08:36
Oh, yeah, you're right. I haven't read the last commit

**Comment by stof** [comment] 2021-09-24 08:57
@maicol07 I suggest you close this issue then (I cannot do it myself, as I'm neither the author nor a maintainer, but only a contributor)

**Comment by maicol07** [comment] 2021-09-24 10:23
> @maicol07 I suggest you close this issue then (I cannot do it myself, as I'm neither the author nor a maintainer, but only a contributor)

I don't know if the OP has fixed his issue yet

**Comment by stof** [comment] 2021-09-24 10:33
@maicol07 ah yeah, I forgot that your reported your own issue in response to a different one.

**Comment by stof** [comment] 2021-09-28 08:36
I tried debugging this in create-react-app, and the error does not come from the Sass compiler at all.
It comes from `postcss-values-parser` (used by postcss) when trying to parse `calc(var(--bs-gutter-y)*-1)`. and given that this is definetely valid CSS, it indicates a bug in `postcss-values-parser`

**Comment by nex3** [comment] 2021-09-28 20:53
Thanks for debugging, @stof! In that case, I'll close this down.

**Closed by nex3** 2021-09-28 20:53 UTC
Labels: bug, needs info
