### ISSUE TITLE
Sass --watch does not watch

### ISSUE THREAD

**Issue by toolbox1972** [sass/dart-sass#573] opened 2019-01-19 14:15 UTC
Made a standard SASS (Dart Sass 1.6.1) installation according to:  https://sass-lang.com/install
`npm install -g sass`

My setup:
node: v11.6.0
sass: 1.16.0
OS:Ubuntu 18.04 LTE

Sending following command:
`sass --no-source-map --watch index.scss index.css`

Result:
- No terminal printout confirmation about [--watch] running.
- If running above command for first time, the CSS is not created.
- Changing below scss [color: red] to [color: blue], does not change the css file, accordingly.

...both files [scss] and [css] are located in the same folder, that is why I do not use the [:] between the files.

**SCSS**
```
$color: red;
.div-1 {background-color: $color;}
```
**CSS** - running manually without [--watch]
`.div-1 {  background-color: red;}`

**Comment by nex3** [comment] 2019-01-24 00:48
> Sending following command:
> `sass index.scss index.css`

This command doesn't include the `--watch` flag, which is necessary for Sass to watch for changes. Is that just a transcription error?

> Result:
> 
> * No terminal printout confirmation about [--watch] running.
> * If running above command for first time, the CSS is not created.
> * Changing below scss [color: red] to [color: blue], does not change the css file, accordingly.

If Sass doesn't even print "Sass is watching for changes", this makes me suspect that [chokidar](https://www.npmjs.com/package/chokidar) isn't sending a "ready" event. Does the command terminate?

How familiar are you with Node.js? I'd really like to know which version of chokidar your Sass installation is using, and what the following JS script prints with that chokidar version:

```js
const chokidar = require('chokidar');

let watcher = chokidar.watch('.', {disableGlobbing: true, usePolling: false});

watcher.on('ready', () => {
  console.log("ready!");
  watcher.close();
});
```

**Comment by nex3** [comment] 2019-01-24 21:37
> I updated the command, since I do use [--no-source-map] and [--watch].
> The command is received and the terminal window does not hang.

What does this mean, exactly? What does the terminal print? Does the command exit immediately?



> I am not that familiar with node.js yet, just start to use it today as part of university courses.
> Can I run the above script with vanilla js? I created a standard webpage and added the script into a *.js, that i connect from my index.php. In the dev tool -> console, I get: "require is not defined".
> 
> I did also run your js script from node.js:
> 
> `trader@black:/tmp2$ node check-chokidar.js `
> 
> ```
> internal/modules/cjs/loader.js:605
>     throw err;
>     ^
> 
> Error: Cannot find module 'chokidar'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:529:25)
>     at Module.require (internal/modules/cjs/loader.js:657:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at Object.<anonymous> (/tmp2/check-chokidar.js:1:80)
>     at Module._compile (internal/modules/cjs/loader.js:721:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
>     at Module.load (internal/modules/cjs/loader.js:620:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
> ```

You'd need to run it with node.js, in a package with chokidar is installed. I can walk you through that if you need, but first, can you try installing Sass [from GitHub](https://github.com/sass/dart-sass/releases/tag/1.16.1) and seeing if that also produces the problem in question?

**Comment by toolbox1972** [comment] 2019-02-05 09:10
The command is received by terminal, exits immediately, without any errors.

**Comment by toolbox1972** [comment] 2019-02-05 09:20
It does work with [--watch] if i download SASS from github.
Problem with npm installation, persists though.

**Comment by nex3** [comment] 2019-02-07 01:57
Okay, so the problem is specific to Node. That's good information.

Try creating the following `package.json` file next to `check-chokidar.js`:

```json
{
  "dependencies": {
    "chokidar": "^2.0.0"
  }
}
```

Run `npm install`, and then run `node check-chokidar.js`.

**Comment by nex3** [comment] 2019-04-25 23:05
I'm going to mark this as a duplicate of #550.

**Closed by nex3** 2019-04-25 23:05 UTC
Labels: bug, needs info
