### ISSUE TITLE
Importing CSS file with sourcemap as SCSS breaks sourcemaps

### ISSUE THREAD

**Issue by mattfelten** [sass/dart-sass#1045] opened 2020-07-22 01:36 UTC
Basically `@import file`, where that file is `file.css` and has a valid sourcemap, will make sourcemaps stop working.

I put together an example here (https://mattfelten.github.io/sass-import-test/import-as-css/) where I created a library file, compiled, and then tested importing both the source and the compiled version.

At [this link](https://mattfelten.github.io/sass-import-test/import-as-css/), which is importing the library as CSS, the sourcemap does not work at all for the entire file.
At [this link](https://mattfelten.github.io/sass-import-test/import-as-scss/), which is importing the source SCSS file, the sourcemap works as intended.

Not sure if this is a bug but it feels like it would be nice to either merge found sourcemaps or completely ignore them.

**Comment by Awjin** [comment] 2020-07-22 20:06
Duplicate of https://github.com/sass/sass/issues/2397 — merging source maps is out-of-scope for Sass, and instead is provided by other libraries. If you are unable to import the library as Sass and need to import the CSS, I would recommend adding a simple processing step that removes the source map comment from the CSS file before importing it.

**Closed by Awjin** 2020-07-22 20:06 UTC
