### ISSUE TITLE
Unexpected exception:RangeError (index): Index out of range: index should be less than 1: 1

### ISSUE THREAD

**Issue by FDiskas** [sass/dart-sass#18] opened 2016-11-01 17:30 UTC
Im using: `1.0.0-alpha.1 compiled with dart2js 1.20.1`
I got the following error:
```bash
Unexpected exception:RangeError (index): Index out of range: index should be less than 1: 1
node_modules/dart-sass/sass.dart.js 4154:17   wrapException
node_modules/dart-sass/sass.dart.js 4104:15   ioore
node_modules/dart-sass/sass.dart.js 17688:22  Environment.getFunction$1
node_modules/dart-sass/sass.dart.js 27465:66  _PerformVisitor.visitFunctionExpression$1
node_modules/dart-sass/sass.dart.js 16014:24  FunctionExpression.accept$1
node_modules/dart-sass/sass.dart.js 27370:75  _PerformVisitor.visitVariableDeclaration$1
node_modules/dart-sass/sass.dart.js 16637:24  VariableDeclaration.accept$1
node_modules/dart-sass/sass.dart.js 31349:41  J.accept$1$x
node_modules/dart-sass/sass.dart.js 28126:13  _PerformVisitor__visitDynamicImport__closure.call$0
node_modules/dart-sass/sass.dart.js 27703:27  _PerformVisitor._withEnvironment$2
```

My environment is:
**package.json**
```json
{
  "name": "untitled",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "dart-sass ./src/main.scss dist/main.css  > ./dist/main.css"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "bootstrap-sass": "^3.3.7"
  },
  "devDependencies": {
    "dart-sass": "^1.0.0-alpha.1"
  }
}
```
**src/main.scss**
```scss
@import "../node_modules/bootstrap-sass/assets/stylesheets/_bootstrap";
```

**Comment by FDiskas** [comment] 2016-11-01 17:37
:mega: Probably I want to mutch. But its good point to test this :)

**Comment by nex3** [comment] 2016-11-01 17:44
This looks like something @kaelig was seeing, but we couldn't figure out what was causing it. Unfortunately, knowing that the culprit is somewhere in all of bootstrap doesn't narrow it down much. Let me know if you can find a more isolated chunk of stylesheet that reproduces this.

**Comment by FDiskas** [comment] 2016-11-01 17:53
`npm install gnomon`

p.s. about benchmark. dart-sass with error returns the following
```
npm run dev | gnomon
```
returns Total   0.0117s

And the node-sass - with successfully builded whole bootstrap
returns: Total   0.0132s

**Comment by FDiskas** [comment] 2016-11-01 17:55
And the error is caused by this line in bootstrap settings scss file
```
$gray-darker:            lighten($gray-base, 13.5%) !default; // #222
```

**Comment by FDiskas** [comment] 2016-11-01 18:08
And all other functions like `ceil, floor, rgba` and some logick like
`(720px + $grid-gutter-width)`
causing this errors

**Comment by nshahan** [comment] 2016-11-01 18:09
I think I am getting a similar issue. I just created a simple test to reproduce the issue.

https://github.com/sass/dart-sass/issues/20

**Comment by nex3** [comment] 2016-11-01 23:40
Fixed by e0fd5ea65c0a533b2e2604e02f4a6916d83dd23e.

**Closed by nex3** 2016-11-01 23:40 UTC
Labels: bug, needs info

**Comment by praharshbhatt** [comment] 2019-12-04 03:00
can anyone help with the same issue `[here](https://github.com/Ali-Azmoud/flutter_xlider/issues/35)`?

**Comment by nshahan** [comment] 2019-12-04 17:26
@praharshbhatt Since you are getting this error from another project entirely the symptom (error message) is the same but the root cause is completely different. Somewhere in the code you are using there is an attempt to perform an index operation with a value that is outside the range of the collection being indexed into.
