### ISSUE TITLE
[Quesition] Will the `@import` syntax be dropped on 1 October 2022?

### ISSUE THREAD

**Issue by joneff** [sass/dart-sass#1674] opened 2022-04-15 10:40 UTC
To quote https://sass-lang.com/blog/the-module-system-is-launched#future-plans:

> One year after this deprecation goes into effect (**1 October 2022 at latest**), we will drop support for `@import` and most global functions entirely. This will involve a major version release for all implementations.

So is this date still relevant? If so, Is there a timeline when dart-sass 2.0.0 alpha / beta / omega will be released? Asking for a friend...

**Comment by jathak** [comment] 2022-04-18 20:35
Duplicate of sass/sass#3276

**Closed by jathak** 2022-04-18 20:35 UTC
