### ISSUE TITLE
[Feature Request] Ability to use @extend with :is

### ISSUE THREAD

**Issue by ggedde** [sass/dart-sass#2135] opened 2023-11-23 00:40 UTC
Is there a way to do this currently?
if not then I would like to request it. Maybe @extend-is, etc.

Example:
```
%ui {
  color: blue;
  &:hover {
    color: red
  }
}

button {
  @extend-is %ui;
}
a {
  @extend-is %ui;
}
.badge {
  @extend-is %ui;
}
```
Output as:
```
:is(button,a,.badge) {
  color: blue;
}
:is(button,a,.badge):hover {
  color: red;
}
```
Instead of:
```
button,
a,
.badge {
  color: blue;
}
button:hover,
a:hover,
.badge:hover {
  color: red;
}
```

**Comment by nex3** [comment] 2023-12-01 00:08
Duplicate of https://github.com/sass/sass/issues/1136

**Closed by nex3** 2023-12-01 00:08 UTC
