### ISSUE TITLE
Fibers package has been obsoleted

### ISSUE THREAD

**Issue by ryanelian** [sass/dart-sass#986] opened 2020-04-23 16:15 UTC
https://github.com/laverdet/node-fibers

> NOTE OF OBSOLESCENCE -- The author of this project recommends you avoid its use if possible. The original version of this module targeted nodejs v0.1.x in early 2011 when JavaScript on the server looked a lot different. Since then async/await, Promises, and Generators were standardized and the ecosystem as a whole has moved in that direction.

Any chance that the npm sass package could function without fibers package while maintaining performance?

With Node 14 being released, there is an issue where sass cannot run in node 10 if Fibers 5 is installed.

(Fibers 5 is compatible with Node 14 and Node 12 only, despite Node 10 LTS is supported until April 2021, while Fibers 4 is not compatible with Node 14!)

**Comment by ryanelian** [comment] 2020-04-23 16:19
By the way, my custom importer is actually promise:

```ts
/**
 * Implements a smarter Sass @import logic,
 * which performs resolution into node_modules and package.json:style!
 * @param source 
 * @param request 
 */
export async function sassImport(source: string, request: string): Promise<string>
```

```ts
export function sassImporter(request: string, source: string, done: (data: ImporterReturnType) => void): void {
    sassImport(source, request).then(resolution => {
        // console.log(source, '+', request, '=', resolution); console.log();
        done({
            file: resolution
        });
    }).catch(error => {
        done(error);
    });
}
```

I wonder if sass can be modified to accept function returning promise directly instead of relying on fibers?

https://api.flutter.dev/flutter/dart-js_util/promiseToFuture.html

**Comment by nex3** [comment] 2020-04-23 18:42
Unfortunately, we can't just switch to using promises. Async/await, promises, and generators are all fundamentally just sugar on top of callback-passing semantics, whereas fibers actually *add power* to the platform. Without `fibers`, there's no way to write a synchronous function that takes an asynchronous callback. This is crucial for Dart Sass's performance because the asynchronous implementation of the compilation logic is much much slower than the synchronous implementation. `fibers` allows us to use the synchronous logic while also calling asynchronous callbacks.

I'm going to mark this as a duplicate of #868, since that's probably the only way we can avoid our dependency on `fibers` while maintaining performance. In the short term, though, if you don't want to use `fibers` your best recourse (and a good idea in general) is to rewrite your importer so it's synchronous anyway.

**Closed by nex3** 2020-04-23 18:42 UTC
