### ISSUE TITLE
Compiled .css file not adhering to hierarchy of comments

### ISSUE THREAD

**Issue by GarryAylott** [sass/dart-sass#1641] opened 2022-02-27 00:15 UTC
### Issue
When compiling from .scss to .css, comments are not left at the top of the file but are pushed underneath (notably when using @use).

### Details/Use Case
When developing WordPress themes there is a comment block needed that tells WP details about the theme and is required to be at the top so it can be recognised as a theme etc. This declaration block/comment is being pushed underneath the compiled style code.

I've seen a couple of older comments raised on this but they look to be closed?

**Comment by jathak** [comment] 2022-03-09 18:11
Duplicate of https://github.com/sass/sass/issues/2848.

CSS from `@use`d modules is always emitted first, and we don't plan to add an exception for comments. If you need a comment to always be at the top of your compiled CSS, we'd recommend adding it in a post-processing step after your Sass is compiled.

**Closed by jathak** 2022-03-09 18:11 UTC
