### ISSUE TITLE
--watch not working as expected on Windows

### ISSUE THREAD

**Issue by maxloh** [sass/dart-sass#753] opened 2019-07-05 09:24 UTC
Hi, after I ran this command on Windows,
````
npx sass .\assets\dev\scss\style.scss:.\assets\css\style.css --style=compressed --source-map "--watch"
````
SASS printed out 
```
Compiled assets\dev\scss\style.scss to assets\css\style.css.
Sass is watching for changes. Press Ctrl-C to stop.
```

but it do not compile `assets\dev\scss\style.scss` automatically after I changed and saved the file.

Is it a bug? If not, how can I fix this?

---

SASS version: `1.22.3 compiled with dart2js 2.4.0`

The complete log are as follows

```
PS C:\Users\Max\Documents\GitHub\maxloh.github.io> npm run watch-css

> maxloh.github.io@2.0.0 watch-css C:\Users\Max\Documents\GitHub\maxloh.github.io
> npm run css-compile -- --watch


> maxloh.github.io@2.0.0 css-compile C:\Users\Max\Documents\GitHub\maxloh.github.io
> npx sass .\assets\dev\scss\style.scss:.\assets\css\style.css --style=compressed --source-map "--watch"

Compiled assets\dev\scss\style.scss to assets\css\style.css.
Sass is watching for changes. Press Ctrl-C to stop.
```

**Comment by nex3** [comment] 2019-07-10 21:54
This is a duplicate of #550. At this point, I've run out of debugging I can do myself without being able to reproduce the issue, so we need someone who can reliably reproduce the issue to dive into the Dart code and see what's going wrong there. See #550 for details.

**Closed by nex3** 2019-07-10 21:54 UTC
