### ISSUE TITLE
dart-sass 1.56.0 - Homebrew SHA256 mismatch

### ISSUE THREAD

**Issue by ellierider** [sass/dart-sass#1825] opened 2022-11-04 14:05 UTC
I'm not sure if this is the correct place to report this, but when updating this morning via homebrew I got a SHA256 mismatch, shown below.

This is on macOS Ventura 13.0 / M1

```
==> Downloading https://github.com/sass/dart-sass/archive/1.56.0.tar.gz
==> Downloading from https://codeload.github.com/sass/dart-sass/tar.gz/refs/tags/1.56.0
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 1fddc66a11847255434227ab38edc3a0c1dbc53bfa9c3a7bc3393eee142fafbb
  Actual: 077365a9d5e3068d14e00d4db6f15d6cda66f8052e9e0452e8bf298c8de7e8ab
```

**Comment by shengslogar** [comment] 2022-11-04 16:10
Same here, upgrading from `1.55.0`. Tag got pushed late last night. Same OS/device.

**Comment by rsanheim** [comment] 2022-11-04 18:23
cross ref https://github.com/sass/homebrew-sass/issues/43

Not sure why the bot pushed an incorrect sha there.  We installed dart-sass manually as a workaround for now.

**Comment by Patronics** [comment] 2022-11-06 09:04
> EDIT: `brew pin sass` to pin your current version until this is sorted.
Thanks, this works as a workaround to let me upgrade everything else installed via homebrew. Only problem is that I'll probably forget to unpin it.

**Comment by mortence** [comment] 2022-11-07 11:11
1. `brew edit sass`
2. replace '`1fddc66a11847255434227ab38edc3a0c1dbc53bfa9c3a7bc3393eee142fafbb`' 
 to  '`077365a9d5e3068d14e00d4db6f15d6cda66f8052e9e0452e8bf298c8de7e8ab`'
3. `brew upgrade sass`

**Comment by robksawyer** [comment] 2022-11-07 20:04
Also getting this error. Yeah, the mismatch is a bit concerning. Any other workarounds?

**Comment by dvaldivia** [comment] 2022-11-07 20:07
I think `brew pin sass` is the best workaround for the time being @robksawyer

**Comment by robksawyer** [comment] 2022-11-07 20:08
I don't have sass installed, so when I run that I get ```Error: sass not installed```

**Comment by nex3** [comment] 2022-11-07 21:46
Duplicate of https://github.com/sass/homebrew-sass/issues/43, please follow that issue for updates.

**Closed by nex3** 2022-11-07 21:46 UTC
