### ISSUE TITLE
Can it fail if there are warnings?

### ISSUE THREAD

**Issue by Ariane-B** [sass/dart-sass#1804] opened 2022-09-19 18:39 UTC
We have an automated merge request pipeline, and occasionally, a developer will not notice they have a deprecation warning on their branch, and code with it will be merged to the main branch. Then other developers suddenly have, say, a slash division deprecation warning, and they have to deal with it, even though they didn't even touch the file in question.

This could all be prevented if we could fail the GitLab pipeline anytime there's any issue whatsoever in the build, including Sass warnings. And for that, we'd need the Sass CLI build command _not_ to return status code 0.

Is there already a way to do this? If not, can it be added?

**Comment by nex3** [comment] 2022-09-19 20:23
Duplicate of sass/dart-sass#633

**Closed by nex3** 2022-09-19 20:23 UTC
