### ISSUE TITLE
Typescript Definition File(s) for JS users

### ISSUE THREAD

**Issue by ProtonScott** [sass/dart-sass#459] opened 2018-08-26 17:06 UTC
I just wanted to open an issue and see if we could scope out the possibility of getting Typescript Definiton Files for this new sass implementation. I know as a JS API user this would come in handy to have as most minders editors can pick up on these files for code assistance as well as the fact that they act as a great way to reference APIs as a developer when referencing an API

Is this something you guys are exploring and/or are open to? I’m researching if there is an easy way you can do it at compilation time when you convert the dart code to JS or if this is something we would need to do mildly more manually. 

I am happy to help however I can

What’s the projects thoughts on this?

[Appendix: More Info On Typescript Definiton Files](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html)

**Comment by nex3** [comment] 2018-08-28 08:26
Duplicate of https://github.com/sass/dart-sass/issues/13.

The short answer is that Dart Sass has the same JS API as Node Sass, which has a definition file [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node-sass/index.d.ts). If there's a way we could better package this up for npm distribution, we'd be happy to take contributions.

**Closed by nex3** 2018-08-28 08:26 UTC
