### ISSUE TITLE
Slow performance when using npm package `sass`

### ISSUE THREAD

**Issue by alex-page** [sass/dart-sass#415] opened 2018-07-20 00:57 UTC
I have been using the npm package for `dart-sass` recently across some projects (
[Sass A11yColor](https://github.com/alex-page/sass-a11ycolor) ). I have noticed that using the homebrew installation of `dart-sass` and the `node-sass` npm package is a lot faster then using the `sass` npm package.

`dart-sass`  homebrew installation:
```
⚡️ sass test.scss style.css | gnomon
   0.7805s

     Total   0.7808s
```

NPM `node-sass` package ran with `node-sass test.scss style.css`
```
⚡️ npm run build:node-sass | gnomon
   0.1152s
   0.0004s   > sass-perf@1.0.0 build:node-sass /Users/alexpage/Sites/sass-perf
   0.0001s   > node-sass test.scss style.css
   0.6985s
   0.0033s   Rendering Complete, saving .css file...
   0.0130s   Wrote CSS to /Users/alexpage/Sites/sass-perf/style.css
   0.0002s

     Total   0.8313s
```

NPM `sass` package ran with `sass test.scss style.css`
```
⚡️ npm run build:sass | gnomon
   0.1159s
   0.0004s   > sass-perf@1.0.0 build:sass /Users/alexpage/Sites/sass-perf
   0.0001s   > sass test.scss style.css
  12.6218s
   0.0002s

     Total   12.7388s
```

I am not sure if there is anything that can be done to get the performance of the homebrew package in the npm package, or what would be causing the performance to drop. If you want me to investigate it further I am happy to. The function that I am running is a binary search moving color values up and down lightness using sass.

I also did some experimentation with `fibers` however I was still confused by the result.

**Comment by nex3** [comment] 2018-07-20 05:21
Duplicate of #113

The `sass` package on Homebrew runs using the Dart VM, while the `sass` package on npm is compiled to JavaScript and run via Node, which is substantially slower. That said, a slowdown of more than 10x is surprising. I'm hoping someone can look into performance-tuning the JavaScript implementation soon, and this will be a good test case.

**Closed by nex3** 2018-07-20 05:21 UTC

**Comment by alex-page** [comment] 2018-07-20 05:40
Thanks @nex3 for the response
